/*
Quant administration API

Testing ProjectsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/quantcdn/quant-admin-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_ProjectsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ProjectsAPIService OrganizationsOrganizationProjectsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organization interface{}

		resp, httpRes, err := apiClient.ProjectsAPI.OrganizationsOrganizationProjectsGet(context.Background(), organization).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService OrganizationsOrganizationProjectsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organization interface{}

		resp, httpRes, err := apiClient.ProjectsAPI.OrganizationsOrganizationProjectsPost(context.Background(), organization).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService OrganizationsOrganizationProjectsProjectDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organization interface{}
		var project interface{}

		resp, httpRes, err := apiClient.ProjectsAPI.OrganizationsOrganizationProjectsProjectDelete(context.Background(), organization, project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService OrganizationsOrganizationProjectsProjectGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organization interface{}
		var project interface{}

		resp, httpRes, err := apiClient.ProjectsAPI.OrganizationsOrganizationProjectsProjectGet(context.Background(), organization, project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProjectsAPIService OrganizationsOrganizationProjectsProjectPatch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var organization interface{}
		var project interface{}

		resp, httpRes, err := apiClient.ProjectsAPI.OrganizationsOrganizationProjectsProjectPatch(context.Background(), organization, project).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
