/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type VariablesAPI interface {

	/*
	BulkSetEnvironmentVariables Bulk set/replace environment variables

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param apiOrganisation The organisation ID
	@param apiApplication The application ID
	@param apiEnvironment The environment ID
	@return VariablesAPIBulkSetEnvironmentVariablesRequest
	*/
	BulkSetEnvironmentVariables(ctx context.Context, apiOrganisation string, apiApplication string, apiEnvironment string) VariablesAPIBulkSetEnvironmentVariablesRequest

	// BulkSetEnvironmentVariablesExecute executes the request
	BulkSetEnvironmentVariablesExecute(r VariablesAPIBulkSetEnvironmentVariablesRequest) (*http.Response, error)

	/*
	DeleteEnvironmentVariable Delete a variable

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param apiOrganisation The organisation ID
	@param apiApplication The application ID
	@param apiEnvironment The environment ID
	@param apiVariable The variable key
	@return VariablesAPIDeleteEnvironmentVariableRequest
	*/
	DeleteEnvironmentVariable(ctx context.Context, apiOrganisation string, apiApplication string, apiEnvironment string, apiVariable string) VariablesAPIDeleteEnvironmentVariableRequest

	// DeleteEnvironmentVariableExecute executes the request
	DeleteEnvironmentVariableExecute(r VariablesAPIDeleteEnvironmentVariableRequest) (*http.Response, error)

	/*
	ListEnvironmentVariables Get all variables for an environment

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param apiOrganisation The organisation ID
	@param apiApplication The application ID
	@param apiEnvironment The environment ID
	@return VariablesAPIListEnvironmentVariablesRequest
	*/
	ListEnvironmentVariables(ctx context.Context, apiOrganisation string, apiApplication string, apiEnvironment string) VariablesAPIListEnvironmentVariablesRequest

	// ListEnvironmentVariablesExecute executes the request
	ListEnvironmentVariablesExecute(r VariablesAPIListEnvironmentVariablesRequest) (*http.Response, error)

	/*
	UpdateEnvironmentVariable Update a variable

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param apiOrganisation The organisation ID
	@param apiApplication The application ID
	@param apiEnvironment The environment ID
	@param apiVariable The variable key
	@return VariablesAPIUpdateEnvironmentVariableRequest
	*/
	UpdateEnvironmentVariable(ctx context.Context, apiOrganisation string, apiApplication string, apiEnvironment string, apiVariable string) VariablesAPIUpdateEnvironmentVariableRequest

	// UpdateEnvironmentVariableExecute executes the request
	UpdateEnvironmentVariableExecute(r VariablesAPIUpdateEnvironmentVariableRequest) (*http.Response, error)
}

// VariablesAPIService VariablesAPI service
type VariablesAPIService service

type VariablesAPIBulkSetEnvironmentVariablesRequest struct {
	ctx context.Context
	ApiService VariablesAPI
	apiOrganisation string
	apiApplication string
	apiEnvironment string
	bulkSetEnvironmentVariablesRequest *BulkSetEnvironmentVariablesRequest
}

func (r VariablesAPIBulkSetEnvironmentVariablesRequest) BulkSetEnvironmentVariablesRequest(bulkSetEnvironmentVariablesRequest BulkSetEnvironmentVariablesRequest) VariablesAPIBulkSetEnvironmentVariablesRequest {
	r.bulkSetEnvironmentVariablesRequest = &bulkSetEnvironmentVariablesRequest
	return r
}

func (r VariablesAPIBulkSetEnvironmentVariablesRequest) Execute() (*http.Response, error) {
	return r.ApiService.BulkSetEnvironmentVariablesExecute(r)
}

/*
BulkSetEnvironmentVariables Bulk set/replace environment variables

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param apiOrganisation The organisation ID
 @param apiApplication The application ID
 @param apiEnvironment The environment ID
 @return VariablesAPIBulkSetEnvironmentVariablesRequest
*/
func (a *VariablesAPIService) BulkSetEnvironmentVariables(ctx context.Context, apiOrganisation string, apiApplication string, apiEnvironment string) VariablesAPIBulkSetEnvironmentVariablesRequest {
	return VariablesAPIBulkSetEnvironmentVariablesRequest{
		ApiService: a,
		ctx: ctx,
		apiOrganisation: apiOrganisation,
		apiApplication: apiApplication,
		apiEnvironment: apiEnvironment,
	}
}

// Execute executes the request
func (a *VariablesAPIService) BulkSetEnvironmentVariablesExecute(r VariablesAPIBulkSetEnvironmentVariablesRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VariablesAPIService.BulkSetEnvironmentVariables")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables"
	localVarPath = strings.Replace(localVarPath, "{"+"api_organisation"+"}", url.PathEscape(parameterValueToString(r.apiOrganisation, "apiOrganisation")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_application"+"}", url.PathEscape(parameterValueToString(r.apiApplication, "apiApplication")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_environment"+"}", url.PathEscape(parameterValueToString(r.apiEnvironment, "apiEnvironment")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.bulkSetEnvironmentVariablesRequest == nil {
		return nil, reportError("bulkSetEnvironmentVariablesRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.bulkSetEnvironmentVariablesRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type VariablesAPIDeleteEnvironmentVariableRequest struct {
	ctx context.Context
	ApiService VariablesAPI
	apiOrganisation string
	apiApplication string
	apiEnvironment string
	apiVariable string
}

func (r VariablesAPIDeleteEnvironmentVariableRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteEnvironmentVariableExecute(r)
}

/*
DeleteEnvironmentVariable Delete a variable

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param apiOrganisation The organisation ID
 @param apiApplication The application ID
 @param apiEnvironment The environment ID
 @param apiVariable The variable key
 @return VariablesAPIDeleteEnvironmentVariableRequest
*/
func (a *VariablesAPIService) DeleteEnvironmentVariable(ctx context.Context, apiOrganisation string, apiApplication string, apiEnvironment string, apiVariable string) VariablesAPIDeleteEnvironmentVariableRequest {
	return VariablesAPIDeleteEnvironmentVariableRequest{
		ApiService: a,
		ctx: ctx,
		apiOrganisation: apiOrganisation,
		apiApplication: apiApplication,
		apiEnvironment: apiEnvironment,
		apiVariable: apiVariable,
	}
}

// Execute executes the request
func (a *VariablesAPIService) DeleteEnvironmentVariableExecute(r VariablesAPIDeleteEnvironmentVariableRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VariablesAPIService.DeleteEnvironmentVariable")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables/{api_variable}"
	localVarPath = strings.Replace(localVarPath, "{"+"api_organisation"+"}", url.PathEscape(parameterValueToString(r.apiOrganisation, "apiOrganisation")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_application"+"}", url.PathEscape(parameterValueToString(r.apiApplication, "apiApplication")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_environment"+"}", url.PathEscape(parameterValueToString(r.apiEnvironment, "apiEnvironment")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_variable"+"}", url.PathEscape(parameterValueToString(r.apiVariable, "apiVariable")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type VariablesAPIListEnvironmentVariablesRequest struct {
	ctx context.Context
	ApiService VariablesAPI
	apiOrganisation string
	apiApplication string
	apiEnvironment string
}

func (r VariablesAPIListEnvironmentVariablesRequest) Execute() (*http.Response, error) {
	return r.ApiService.ListEnvironmentVariablesExecute(r)
}

/*
ListEnvironmentVariables Get all variables for an environment

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param apiOrganisation The organisation ID
 @param apiApplication The application ID
 @param apiEnvironment The environment ID
 @return VariablesAPIListEnvironmentVariablesRequest
*/
func (a *VariablesAPIService) ListEnvironmentVariables(ctx context.Context, apiOrganisation string, apiApplication string, apiEnvironment string) VariablesAPIListEnvironmentVariablesRequest {
	return VariablesAPIListEnvironmentVariablesRequest{
		ApiService: a,
		ctx: ctx,
		apiOrganisation: apiOrganisation,
		apiApplication: apiApplication,
		apiEnvironment: apiEnvironment,
	}
}

// Execute executes the request
func (a *VariablesAPIService) ListEnvironmentVariablesExecute(r VariablesAPIListEnvironmentVariablesRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VariablesAPIService.ListEnvironmentVariables")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables"
	localVarPath = strings.Replace(localVarPath, "{"+"api_organisation"+"}", url.PathEscape(parameterValueToString(r.apiOrganisation, "apiOrganisation")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_application"+"}", url.PathEscape(parameterValueToString(r.apiApplication, "apiApplication")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_environment"+"}", url.PathEscape(parameterValueToString(r.apiEnvironment, "apiEnvironment")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type VariablesAPIUpdateEnvironmentVariableRequest struct {
	ctx context.Context
	ApiService VariablesAPI
	apiOrganisation string
	apiApplication string
	apiEnvironment string
	apiVariable string
	updateEnvironmentVariableRequest *UpdateEnvironmentVariableRequest
}

func (r VariablesAPIUpdateEnvironmentVariableRequest) UpdateEnvironmentVariableRequest(updateEnvironmentVariableRequest UpdateEnvironmentVariableRequest) VariablesAPIUpdateEnvironmentVariableRequest {
	r.updateEnvironmentVariableRequest = &updateEnvironmentVariableRequest
	return r
}

func (r VariablesAPIUpdateEnvironmentVariableRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateEnvironmentVariableExecute(r)
}

/*
UpdateEnvironmentVariable Update a variable

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param apiOrganisation The organisation ID
 @param apiApplication The application ID
 @param apiEnvironment The environment ID
 @param apiVariable The variable key
 @return VariablesAPIUpdateEnvironmentVariableRequest
*/
func (a *VariablesAPIService) UpdateEnvironmentVariable(ctx context.Context, apiOrganisation string, apiApplication string, apiEnvironment string, apiVariable string) VariablesAPIUpdateEnvironmentVariableRequest {
	return VariablesAPIUpdateEnvironmentVariableRequest{
		ApiService: a,
		ctx: ctx,
		apiOrganisation: apiOrganisation,
		apiApplication: apiApplication,
		apiEnvironment: apiEnvironment,
		apiVariable: apiVariable,
	}
}

// Execute executes the request
func (a *VariablesAPIService) UpdateEnvironmentVariableExecute(r VariablesAPIUpdateEnvironmentVariableRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VariablesAPIService.UpdateEnvironmentVariable")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{api_organisation}/applications/{api_application}/environments/{api_environment}/variables/{api_variable}"
	localVarPath = strings.Replace(localVarPath, "{"+"api_organisation"+"}", url.PathEscape(parameterValueToString(r.apiOrganisation, "apiOrganisation")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_application"+"}", url.PathEscape(parameterValueToString(r.apiApplication, "apiApplication")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_environment"+"}", url.PathEscape(parameterValueToString(r.apiEnvironment, "apiEnvironment")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"api_variable"+"}", url.PathEscape(parameterValueToString(r.apiVariable, "apiVariable")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateEnvironmentVariableRequest == nil {
		return nil, reportError("updateEnvironmentVariableRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateEnvironmentVariableRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
