/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.17.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type AISlackBotsAPI interface {

	/*
	CreateSlackBot Create Slack Bot

	Creates a new Slack bot with inline AI agent configuration. A backing agent is created automatically — callers do not need to manage agents separately.
     *
     * **Setup Types:**
     * - `quant`: Quant-managed Slack app — uses shared OAuth credentials
     * - `byo`: Bring Your Own — customer provides their own Slack app credentials

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param organisation The organisation ID
	@return AISlackBotsAPICreateSlackBotRequest
	*/
	CreateSlackBot(ctx context.Context, organisation string) AISlackBotsAPICreateSlackBotRequest

	// CreateSlackBotExecute executes the request
	//  @return CreateSlackBot201Response
	CreateSlackBotExecute(r AISlackBotsAPICreateSlackBotRequest) (*CreateSlackBot201Response, *http.Response, error)

	/*
	DeleteSlackBot Delete Slack Bot

	Permanently deletes a Slack bot, disconnects it from the workspace, and deletes its backing AI agent.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param organisation The organisation ID
	@param botId The Slack bot ID
	@return AISlackBotsAPIDeleteSlackBotRequest
	*/
	DeleteSlackBot(ctx context.Context, organisation string, botId string) AISlackBotsAPIDeleteSlackBotRequest

	// DeleteSlackBotExecute executes the request
	//  @return DeleteSlackBot200Response
	DeleteSlackBotExecute(r AISlackBotsAPIDeleteSlackBotRequest) (*DeleteSlackBot200Response, *http.Response, error)

	/*
	GetSlackBot Get Slack Bot

	Retrieves details for a specific Slack bot including its configuration, connection status, and flattened agent configuration.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param organisation The organisation ID
	@param botId The Slack bot ID
	@return AISlackBotsAPIGetSlackBotRequest
	*/
	GetSlackBot(ctx context.Context, organisation string, botId string) AISlackBotsAPIGetSlackBotRequest

	// GetSlackBotExecute executes the request
	//  @return GetSlackBot200Response
	GetSlackBotExecute(r AISlackBotsAPIGetSlackBotRequest) (*GetSlackBot200Response, *http.Response, error)

	/*
	ListSlackBots List Slack Bots

	Lists all Slack bots configured for the organization. Each bot is backed by an AI agent and can be connected to a Slack workspace. Agent configuration fields are flattened onto each bot object.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param organisation The organisation ID
	@return AISlackBotsAPIListSlackBotsRequest
	*/
	ListSlackBots(ctx context.Context, organisation string) AISlackBotsAPIListSlackBotsRequest

	// ListSlackBotsExecute executes the request
	//  @return ListSlackBots200Response
	ListSlackBotsExecute(r AISlackBotsAPIListSlackBotsRequest) (*ListSlackBots200Response, *http.Response, error)

	/*
	SearchSlackWorkspaceChannels Search Slack Workspace Channels

	Searches channels in the Slack workspace connected to this bot. Requires the bot to be connected via OAuth.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param organisation The organisation ID
	@param botId The Slack bot ID
	@return AISlackBotsAPISearchSlackWorkspaceChannelsRequest
	*/
	SearchSlackWorkspaceChannels(ctx context.Context, organisation string, botId string) AISlackBotsAPISearchSlackWorkspaceChannelsRequest

	// SearchSlackWorkspaceChannelsExecute executes the request
	//  @return SearchSlackWorkspaceChannels200Response
	SearchSlackWorkspaceChannelsExecute(r AISlackBotsAPISearchSlackWorkspaceChannelsRequest) (*SearchSlackWorkspaceChannels200Response, *http.Response, error)

	/*
	SearchSlackWorkspaceUsers Search Slack Workspace Users

	Searches users in the Slack workspace connected to this bot. Requires the bot to be connected via OAuth.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param organisation The organisation ID
	@param botId The Slack bot ID
	@return AISlackBotsAPISearchSlackWorkspaceUsersRequest
	*/
	SearchSlackWorkspaceUsers(ctx context.Context, organisation string, botId string) AISlackBotsAPISearchSlackWorkspaceUsersRequest

	// SearchSlackWorkspaceUsersExecute executes the request
	//  @return SearchSlackWorkspaceUsers200Response
	SearchSlackWorkspaceUsersExecute(r AISlackBotsAPISearchSlackWorkspaceUsersRequest) (*SearchSlackWorkspaceUsers200Response, *http.Response, error)

	/*
	UpdateSlackBot Update Slack Bot

	Updates a Slack bot's configuration and/or its backing agent. Only provided fields are updated.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param organisation The organisation ID
	@param botId The Slack bot ID
	@return AISlackBotsAPIUpdateSlackBotRequest
	*/
	UpdateSlackBot(ctx context.Context, organisation string, botId string) AISlackBotsAPIUpdateSlackBotRequest

	// UpdateSlackBotExecute executes the request
	//  @return CreateSlackBot201Response
	UpdateSlackBotExecute(r AISlackBotsAPIUpdateSlackBotRequest) (*CreateSlackBot201Response, *http.Response, error)
}

// AISlackBotsAPIService AISlackBotsAPI service
type AISlackBotsAPIService service

type AISlackBotsAPICreateSlackBotRequest struct {
	ctx context.Context
	ApiService AISlackBotsAPI
	organisation string
	createSlackBotRequest *CreateSlackBotRequest
}

func (r AISlackBotsAPICreateSlackBotRequest) CreateSlackBotRequest(createSlackBotRequest CreateSlackBotRequest) AISlackBotsAPICreateSlackBotRequest {
	r.createSlackBotRequest = &createSlackBotRequest
	return r
}

func (r AISlackBotsAPICreateSlackBotRequest) Execute() (*CreateSlackBot201Response, *http.Response, error) {
	return r.ApiService.CreateSlackBotExecute(r)
}

/*
CreateSlackBot Create Slack Bot

Creates a new Slack bot with inline AI agent configuration. A backing agent is created automatically — callers do not need to manage agents separately.
     *
     * **Setup Types:**
     * - `quant`: Quant-managed Slack app — uses shared OAuth credentials
     * - `byo`: Bring Your Own — customer provides their own Slack app credentials

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param organisation The organisation ID
 @return AISlackBotsAPICreateSlackBotRequest
*/
func (a *AISlackBotsAPIService) CreateSlackBot(ctx context.Context, organisation string) AISlackBotsAPICreateSlackBotRequest {
	return AISlackBotsAPICreateSlackBotRequest{
		ApiService: a,
		ctx: ctx,
		organisation: organisation,
	}
}

// Execute executes the request
//  @return CreateSlackBot201Response
func (a *AISlackBotsAPIService) CreateSlackBotExecute(r AISlackBotsAPICreateSlackBotRequest) (*CreateSlackBot201Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CreateSlackBot201Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AISlackBotsAPIService.CreateSlackBot")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{organisation}/ai/slack-bots"
	localVarPath = strings.Replace(localVarPath, "{"+"organisation"+"}", url.PathEscape(parameterValueToString(r.organisation, "organisation")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createSlackBotRequest == nil {
		return localVarReturnValue, nil, reportError("createSlackBotRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createSlackBotRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AISlackBotsAPIDeleteSlackBotRequest struct {
	ctx context.Context
	ApiService AISlackBotsAPI
	organisation string
	botId string
}

func (r AISlackBotsAPIDeleteSlackBotRequest) Execute() (*DeleteSlackBot200Response, *http.Response, error) {
	return r.ApiService.DeleteSlackBotExecute(r)
}

/*
DeleteSlackBot Delete Slack Bot

Permanently deletes a Slack bot, disconnects it from the workspace, and deletes its backing AI agent.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param organisation The organisation ID
 @param botId The Slack bot ID
 @return AISlackBotsAPIDeleteSlackBotRequest
*/
func (a *AISlackBotsAPIService) DeleteSlackBot(ctx context.Context, organisation string, botId string) AISlackBotsAPIDeleteSlackBotRequest {
	return AISlackBotsAPIDeleteSlackBotRequest{
		ApiService: a,
		ctx: ctx,
		organisation: organisation,
		botId: botId,
	}
}

// Execute executes the request
//  @return DeleteSlackBot200Response
func (a *AISlackBotsAPIService) DeleteSlackBotExecute(r AISlackBotsAPIDeleteSlackBotRequest) (*DeleteSlackBot200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DeleteSlackBot200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AISlackBotsAPIService.DeleteSlackBot")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{organisation}/ai/slack-bots/{botId}"
	localVarPath = strings.Replace(localVarPath, "{"+"organisation"+"}", url.PathEscape(parameterValueToString(r.organisation, "organisation")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"botId"+"}", url.PathEscape(parameterValueToString(r.botId, "botId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AISlackBotsAPIGetSlackBotRequest struct {
	ctx context.Context
	ApiService AISlackBotsAPI
	organisation string
	botId string
}

func (r AISlackBotsAPIGetSlackBotRequest) Execute() (*GetSlackBot200Response, *http.Response, error) {
	return r.ApiService.GetSlackBotExecute(r)
}

/*
GetSlackBot Get Slack Bot

Retrieves details for a specific Slack bot including its configuration, connection status, and flattened agent configuration.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param organisation The organisation ID
 @param botId The Slack bot ID
 @return AISlackBotsAPIGetSlackBotRequest
*/
func (a *AISlackBotsAPIService) GetSlackBot(ctx context.Context, organisation string, botId string) AISlackBotsAPIGetSlackBotRequest {
	return AISlackBotsAPIGetSlackBotRequest{
		ApiService: a,
		ctx: ctx,
		organisation: organisation,
		botId: botId,
	}
}

// Execute executes the request
//  @return GetSlackBot200Response
func (a *AISlackBotsAPIService) GetSlackBotExecute(r AISlackBotsAPIGetSlackBotRequest) (*GetSlackBot200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetSlackBot200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AISlackBotsAPIService.GetSlackBot")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{organisation}/ai/slack-bots/{botId}"
	localVarPath = strings.Replace(localVarPath, "{"+"organisation"+"}", url.PathEscape(parameterValueToString(r.organisation, "organisation")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"botId"+"}", url.PathEscape(parameterValueToString(r.botId, "botId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AISlackBotsAPIListSlackBotsRequest struct {
	ctx context.Context
	ApiService AISlackBotsAPI
	organisation string
}

func (r AISlackBotsAPIListSlackBotsRequest) Execute() (*ListSlackBots200Response, *http.Response, error) {
	return r.ApiService.ListSlackBotsExecute(r)
}

/*
ListSlackBots List Slack Bots

Lists all Slack bots configured for the organization. Each bot is backed by an AI agent and can be connected to a Slack workspace. Agent configuration fields are flattened onto each bot object.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param organisation The organisation ID
 @return AISlackBotsAPIListSlackBotsRequest
*/
func (a *AISlackBotsAPIService) ListSlackBots(ctx context.Context, organisation string) AISlackBotsAPIListSlackBotsRequest {
	return AISlackBotsAPIListSlackBotsRequest{
		ApiService: a,
		ctx: ctx,
		organisation: organisation,
	}
}

// Execute executes the request
//  @return ListSlackBots200Response
func (a *AISlackBotsAPIService) ListSlackBotsExecute(r AISlackBotsAPIListSlackBotsRequest) (*ListSlackBots200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListSlackBots200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AISlackBotsAPIService.ListSlackBots")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{organisation}/ai/slack-bots"
	localVarPath = strings.Replace(localVarPath, "{"+"organisation"+"}", url.PathEscape(parameterValueToString(r.organisation, "organisation")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AISlackBotsAPISearchSlackWorkspaceChannelsRequest struct {
	ctx context.Context
	ApiService AISlackBotsAPI
	organisation string
	botId string
	q *string
}

// Search query to filter channels by name
func (r AISlackBotsAPISearchSlackWorkspaceChannelsRequest) Q(q string) AISlackBotsAPISearchSlackWorkspaceChannelsRequest {
	r.q = &q
	return r
}

func (r AISlackBotsAPISearchSlackWorkspaceChannelsRequest) Execute() (*SearchSlackWorkspaceChannels200Response, *http.Response, error) {
	return r.ApiService.SearchSlackWorkspaceChannelsExecute(r)
}

/*
SearchSlackWorkspaceChannels Search Slack Workspace Channels

Searches channels in the Slack workspace connected to this bot. Requires the bot to be connected via OAuth.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param organisation The organisation ID
 @param botId The Slack bot ID
 @return AISlackBotsAPISearchSlackWorkspaceChannelsRequest
*/
func (a *AISlackBotsAPIService) SearchSlackWorkspaceChannels(ctx context.Context, organisation string, botId string) AISlackBotsAPISearchSlackWorkspaceChannelsRequest {
	return AISlackBotsAPISearchSlackWorkspaceChannelsRequest{
		ApiService: a,
		ctx: ctx,
		organisation: organisation,
		botId: botId,
	}
}

// Execute executes the request
//  @return SearchSlackWorkspaceChannels200Response
func (a *AISlackBotsAPIService) SearchSlackWorkspaceChannelsExecute(r AISlackBotsAPISearchSlackWorkspaceChannelsRequest) (*SearchSlackWorkspaceChannels200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SearchSlackWorkspaceChannels200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AISlackBotsAPIService.SearchSlackWorkspaceChannels")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{organisation}/ai/slack-bots/{botId}/workspace/channels"
	localVarPath = strings.Replace(localVarPath, "{"+"organisation"+"}", url.PathEscape(parameterValueToString(r.organisation, "organisation")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"botId"+"}", url.PathEscape(parameterValueToString(r.botId, "botId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.q != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "q", r.q, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AISlackBotsAPISearchSlackWorkspaceUsersRequest struct {
	ctx context.Context
	ApiService AISlackBotsAPI
	organisation string
	botId string
	q *string
}

// Search query to filter users by name
func (r AISlackBotsAPISearchSlackWorkspaceUsersRequest) Q(q string) AISlackBotsAPISearchSlackWorkspaceUsersRequest {
	r.q = &q
	return r
}

func (r AISlackBotsAPISearchSlackWorkspaceUsersRequest) Execute() (*SearchSlackWorkspaceUsers200Response, *http.Response, error) {
	return r.ApiService.SearchSlackWorkspaceUsersExecute(r)
}

/*
SearchSlackWorkspaceUsers Search Slack Workspace Users

Searches users in the Slack workspace connected to this bot. Requires the bot to be connected via OAuth.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param organisation The organisation ID
 @param botId The Slack bot ID
 @return AISlackBotsAPISearchSlackWorkspaceUsersRequest
*/
func (a *AISlackBotsAPIService) SearchSlackWorkspaceUsers(ctx context.Context, organisation string, botId string) AISlackBotsAPISearchSlackWorkspaceUsersRequest {
	return AISlackBotsAPISearchSlackWorkspaceUsersRequest{
		ApiService: a,
		ctx: ctx,
		organisation: organisation,
		botId: botId,
	}
}

// Execute executes the request
//  @return SearchSlackWorkspaceUsers200Response
func (a *AISlackBotsAPIService) SearchSlackWorkspaceUsersExecute(r AISlackBotsAPISearchSlackWorkspaceUsersRequest) (*SearchSlackWorkspaceUsers200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SearchSlackWorkspaceUsers200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AISlackBotsAPIService.SearchSlackWorkspaceUsers")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{organisation}/ai/slack-bots/{botId}/workspace/users"
	localVarPath = strings.Replace(localVarPath, "{"+"organisation"+"}", url.PathEscape(parameterValueToString(r.organisation, "organisation")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"botId"+"}", url.PathEscape(parameterValueToString(r.botId, "botId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.q != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "q", r.q, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AISlackBotsAPIUpdateSlackBotRequest struct {
	ctx context.Context
	ApiService AISlackBotsAPI
	organisation string
	botId string
	updateSlackBotRequest *UpdateSlackBotRequest
}

func (r AISlackBotsAPIUpdateSlackBotRequest) UpdateSlackBotRequest(updateSlackBotRequest UpdateSlackBotRequest) AISlackBotsAPIUpdateSlackBotRequest {
	r.updateSlackBotRequest = &updateSlackBotRequest
	return r
}

func (r AISlackBotsAPIUpdateSlackBotRequest) Execute() (*CreateSlackBot201Response, *http.Response, error) {
	return r.ApiService.UpdateSlackBotExecute(r)
}

/*
UpdateSlackBot Update Slack Bot

Updates a Slack bot's configuration and/or its backing agent. Only provided fields are updated.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param organisation The organisation ID
 @param botId The Slack bot ID
 @return AISlackBotsAPIUpdateSlackBotRequest
*/
func (a *AISlackBotsAPIService) UpdateSlackBot(ctx context.Context, organisation string, botId string) AISlackBotsAPIUpdateSlackBotRequest {
	return AISlackBotsAPIUpdateSlackBotRequest{
		ApiService: a,
		ctx: ctx,
		organisation: organisation,
		botId: botId,
	}
}

// Execute executes the request
//  @return CreateSlackBot201Response
func (a *AISlackBotsAPIService) UpdateSlackBotExecute(r AISlackBotsAPIUpdateSlackBotRequest) (*CreateSlackBot201Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CreateSlackBot201Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AISlackBotsAPIService.UpdateSlackBot")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v3/organizations/{organisation}/ai/slack-bots/{botId}"
	localVarPath = strings.Replace(localVarPath, "{"+"organisation"+"}", url.PathEscape(parameterValueToString(r.organisation, "organisation")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"botId"+"}", url.PathEscape(parameterValueToString(r.botId, "botId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateSlackBotRequest == nil {
		return localVarReturnValue, nil, reportError("updateSlackBotRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateSlackBotRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
