/*
Quant administration API

The Quant administration API provides programmatic access to manage projects within your available organizations. 

API version: 2.0.0
Contact: apiteam@quantcdn.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RuleProxyRequestWafConfigNotifyConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuleProxyRequestWafConfigNotifyConfig{}

// RuleProxyRequestWafConfigNotifyConfig struct for RuleProxyRequestWafConfigNotifyConfig
type RuleProxyRequestWafConfigNotifyConfig struct {
	OriginStatusCode []int64 `json:"origin_status_code,omitempty"`
	Period *int64 `json:"period,omitempty"`
	SlackWebhook *string `json:"slack_webhook,omitempty"`
}

// NewRuleProxyRequestWafConfigNotifyConfig instantiates a new RuleProxyRequestWafConfigNotifyConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuleProxyRequestWafConfigNotifyConfig() *RuleProxyRequestWafConfigNotifyConfig {
	this := RuleProxyRequestWafConfigNotifyConfig{}
	return &this
}

// NewRuleProxyRequestWafConfigNotifyConfigWithDefaults instantiates a new RuleProxyRequestWafConfigNotifyConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleProxyRequestWafConfigNotifyConfigWithDefaults() *RuleProxyRequestWafConfigNotifyConfig {
	this := RuleProxyRequestWafConfigNotifyConfig{}
	return &this
}

// GetOriginStatusCode returns the OriginStatusCode field value if set, zero value otherwise.
func (o *RuleProxyRequestWafConfigNotifyConfig) GetOriginStatusCode() []int64 {
	if o == nil || IsNil(o.OriginStatusCode) {
		var ret []int64
		return ret
	}
	return o.OriginStatusCode
}

// GetOriginStatusCodeOk returns a tuple with the OriginStatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleProxyRequestWafConfigNotifyConfig) GetOriginStatusCodeOk() ([]int64, bool) {
	if o == nil || IsNil(o.OriginStatusCode) {
		return nil, false
	}
	return o.OriginStatusCode, true
}

// HasOriginStatusCode returns a boolean if a field has been set.
func (o *RuleProxyRequestWafConfigNotifyConfig) HasOriginStatusCode() bool {
	if o != nil && !IsNil(o.OriginStatusCode) {
		return true
	}

	return false
}

// SetOriginStatusCode gets a reference to the given []int64 and assigns it to the OriginStatusCode field.
func (o *RuleProxyRequestWafConfigNotifyConfig) SetOriginStatusCode(v []int64) {
	o.OriginStatusCode = v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *RuleProxyRequestWafConfigNotifyConfig) GetPeriod() int64 {
	if o == nil || IsNil(o.Period) {
		var ret int64
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleProxyRequestWafConfigNotifyConfig) GetPeriodOk() (*int64, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *RuleProxyRequestWafConfigNotifyConfig) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given int64 and assigns it to the Period field.
func (o *RuleProxyRequestWafConfigNotifyConfig) SetPeriod(v int64) {
	o.Period = &v
}

// GetSlackWebhook returns the SlackWebhook field value if set, zero value otherwise.
func (o *RuleProxyRequestWafConfigNotifyConfig) GetSlackWebhook() string {
	if o == nil || IsNil(o.SlackWebhook) {
		var ret string
		return ret
	}
	return *o.SlackWebhook
}

// GetSlackWebhookOk returns a tuple with the SlackWebhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleProxyRequestWafConfigNotifyConfig) GetSlackWebhookOk() (*string, bool) {
	if o == nil || IsNil(o.SlackWebhook) {
		return nil, false
	}
	return o.SlackWebhook, true
}

// HasSlackWebhook returns a boolean if a field has been set.
func (o *RuleProxyRequestWafConfigNotifyConfig) HasSlackWebhook() bool {
	if o != nil && !IsNil(o.SlackWebhook) {
		return true
	}

	return false
}

// SetSlackWebhook gets a reference to the given string and assigns it to the SlackWebhook field.
func (o *RuleProxyRequestWafConfigNotifyConfig) SetSlackWebhook(v string) {
	o.SlackWebhook = &v
}

func (o RuleProxyRequestWafConfigNotifyConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuleProxyRequestWafConfigNotifyConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OriginStatusCode) {
		toSerialize["origin_status_code"] = o.OriginStatusCode
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.SlackWebhook) {
		toSerialize["slack_webhook"] = o.SlackWebhook
	}
	return toSerialize, nil
}

type NullableRuleProxyRequestWafConfigNotifyConfig struct {
	value *RuleProxyRequestWafConfigNotifyConfig
	isSet bool
}

func (v NullableRuleProxyRequestWafConfigNotifyConfig) Get() *RuleProxyRequestWafConfigNotifyConfig {
	return v.value
}

func (v *NullableRuleProxyRequestWafConfigNotifyConfig) Set(val *RuleProxyRequestWafConfigNotifyConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleProxyRequestWafConfigNotifyConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleProxyRequestWafConfigNotifyConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleProxyRequestWafConfigNotifyConfig(val *RuleProxyRequestWafConfigNotifyConfig) *NullableRuleProxyRequestWafConfigNotifyConfig {
	return &NullableRuleProxyRequestWafConfigNotifyConfig{value: val, isSet: true}
}

func (v NullableRuleProxyRequestWafConfigNotifyConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleProxyRequestWafConfigNotifyConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


