/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"fmt"
)

// checks if the ValidateComposeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateComposeRequest{}

// ValidateComposeRequest struct for ValidateComposeRequest
type ValidateComposeRequest struct {
	// The docker-compose.yml file content as a string
	Compose string `json:"compose"`
	// Optional image tag suffix (query parameter takes precedence)
	ImageSuffix *string `json:"imageSuffix,omitempty" validate:"regexp=^[a-z0-9]([a-z0-9-]*[a-z0-9])?$"`
	// Optional application name for context
	Application *string `json:"application,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ValidateComposeRequest ValidateComposeRequest

// NewValidateComposeRequest instantiates a new ValidateComposeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateComposeRequest(compose string) *ValidateComposeRequest {
	this := ValidateComposeRequest{}
	this.Compose = compose
	return &this
}

// NewValidateComposeRequestWithDefaults instantiates a new ValidateComposeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateComposeRequestWithDefaults() *ValidateComposeRequest {
	this := ValidateComposeRequest{}
	return &this
}

// GetCompose returns the Compose field value
func (o *ValidateComposeRequest) GetCompose() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Compose
}

// GetComposeOk returns a tuple with the Compose field value
// and a boolean to check if the value has been set.
func (o *ValidateComposeRequest) GetComposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Compose, true
}

// SetCompose sets field value
func (o *ValidateComposeRequest) SetCompose(v string) {
	o.Compose = v
}

// GetImageSuffix returns the ImageSuffix field value if set, zero value otherwise.
func (o *ValidateComposeRequest) GetImageSuffix() string {
	if o == nil || IsNil(o.ImageSuffix) {
		var ret string
		return ret
	}
	return *o.ImageSuffix
}

// GetImageSuffixOk returns a tuple with the ImageSuffix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateComposeRequest) GetImageSuffixOk() (*string, bool) {
	if o == nil || IsNil(o.ImageSuffix) {
		return nil, false
	}
	return o.ImageSuffix, true
}

// HasImageSuffix returns a boolean if a field has been set.
func (o *ValidateComposeRequest) HasImageSuffix() bool {
	if o != nil && !IsNil(o.ImageSuffix) {
		return true
	}

	return false
}

// SetImageSuffix gets a reference to the given string and assigns it to the ImageSuffix field.
func (o *ValidateComposeRequest) SetImageSuffix(v string) {
	o.ImageSuffix = &v
}

// GetApplication returns the Application field value if set, zero value otherwise.
func (o *ValidateComposeRequest) GetApplication() string {
	if o == nil || IsNil(o.Application) {
		var ret string
		return ret
	}
	return *o.Application
}

// GetApplicationOk returns a tuple with the Application field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateComposeRequest) GetApplicationOk() (*string, bool) {
	if o == nil || IsNil(o.Application) {
		return nil, false
	}
	return o.Application, true
}

// HasApplication returns a boolean if a field has been set.
func (o *ValidateComposeRequest) HasApplication() bool {
	if o != nil && !IsNil(o.Application) {
		return true
	}

	return false
}

// SetApplication gets a reference to the given string and assigns it to the Application field.
func (o *ValidateComposeRequest) SetApplication(v string) {
	o.Application = &v
}

func (o ValidateComposeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateComposeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["compose"] = o.Compose
	if !IsNil(o.ImageSuffix) {
		toSerialize["imageSuffix"] = o.ImageSuffix
	}
	if !IsNil(o.Application) {
		toSerialize["application"] = o.Application
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ValidateComposeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"compose",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateComposeRequest := _ValidateComposeRequest{}

	err = json.Unmarshal(data, &varValidateComposeRequest)

	if err != nil {
		return err
	}

	*o = ValidateComposeRequest(varValidateComposeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "compose")
		delete(additionalProperties, "imageSuffix")
		delete(additionalProperties, "application")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableValidateComposeRequest struct {
	value *ValidateComposeRequest
	isSet bool
}

func (v NullableValidateComposeRequest) Get() *ValidateComposeRequest {
	return v.value
}

func (v *NullableValidateComposeRequest) Set(val *ValidateComposeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateComposeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateComposeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateComposeRequest(val *ValidateComposeRequest) *NullableValidateComposeRequest {
	return &NullableValidateComposeRequest{value: val, isSet: true}
}

func (v NullableValidateComposeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateComposeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


