/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
)

// checks if the ChatInference200ResponseUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatInference200ResponseUsage{}

// ChatInference200ResponseUsage Token usage information
type ChatInference200ResponseUsage struct {
	// Number of input tokens
	InputTokens *int32 `json:"inputTokens,omitempty"`
	// Number of output tokens
	OutputTokens *int32 `json:"outputTokens,omitempty"`
	// Total tokens consumed
	TotalTokens *int32 `json:"totalTokens,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChatInference200ResponseUsage ChatInference200ResponseUsage

// NewChatInference200ResponseUsage instantiates a new ChatInference200ResponseUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatInference200ResponseUsage() *ChatInference200ResponseUsage {
	this := ChatInference200ResponseUsage{}
	return &this
}

// NewChatInference200ResponseUsageWithDefaults instantiates a new ChatInference200ResponseUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatInference200ResponseUsageWithDefaults() *ChatInference200ResponseUsage {
	this := ChatInference200ResponseUsage{}
	return &this
}

// GetInputTokens returns the InputTokens field value if set, zero value otherwise.
func (o *ChatInference200ResponseUsage) GetInputTokens() int32 {
	if o == nil || IsNil(o.InputTokens) {
		var ret int32
		return ret
	}
	return *o.InputTokens
}

// GetInputTokensOk returns a tuple with the InputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatInference200ResponseUsage) GetInputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.InputTokens) {
		return nil, false
	}
	return o.InputTokens, true
}

// HasInputTokens returns a boolean if a field has been set.
func (o *ChatInference200ResponseUsage) HasInputTokens() bool {
	if o != nil && !IsNil(o.InputTokens) {
		return true
	}

	return false
}

// SetInputTokens gets a reference to the given int32 and assigns it to the InputTokens field.
func (o *ChatInference200ResponseUsage) SetInputTokens(v int32) {
	o.InputTokens = &v
}

// GetOutputTokens returns the OutputTokens field value if set, zero value otherwise.
func (o *ChatInference200ResponseUsage) GetOutputTokens() int32 {
	if o == nil || IsNil(o.OutputTokens) {
		var ret int32
		return ret
	}
	return *o.OutputTokens
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatInference200ResponseUsage) GetOutputTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.OutputTokens) {
		return nil, false
	}
	return o.OutputTokens, true
}

// HasOutputTokens returns a boolean if a field has been set.
func (o *ChatInference200ResponseUsage) HasOutputTokens() bool {
	if o != nil && !IsNil(o.OutputTokens) {
		return true
	}

	return false
}

// SetOutputTokens gets a reference to the given int32 and assigns it to the OutputTokens field.
func (o *ChatInference200ResponseUsage) SetOutputTokens(v int32) {
	o.OutputTokens = &v
}

// GetTotalTokens returns the TotalTokens field value if set, zero value otherwise.
func (o *ChatInference200ResponseUsage) GetTotalTokens() int32 {
	if o == nil || IsNil(o.TotalTokens) {
		var ret int32
		return ret
	}
	return *o.TotalTokens
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatInference200ResponseUsage) GetTotalTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTokens) {
		return nil, false
	}
	return o.TotalTokens, true
}

// HasTotalTokens returns a boolean if a field has been set.
func (o *ChatInference200ResponseUsage) HasTotalTokens() bool {
	if o != nil && !IsNil(o.TotalTokens) {
		return true
	}

	return false
}

// SetTotalTokens gets a reference to the given int32 and assigns it to the TotalTokens field.
func (o *ChatInference200ResponseUsage) SetTotalTokens(v int32) {
	o.TotalTokens = &v
}

func (o ChatInference200ResponseUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatInference200ResponseUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InputTokens) {
		toSerialize["inputTokens"] = o.InputTokens
	}
	if !IsNil(o.OutputTokens) {
		toSerialize["outputTokens"] = o.OutputTokens
	}
	if !IsNil(o.TotalTokens) {
		toSerialize["totalTokens"] = o.TotalTokens
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChatInference200ResponseUsage) UnmarshalJSON(data []byte) (err error) {
	varChatInference200ResponseUsage := _ChatInference200ResponseUsage{}

	err = json.Unmarshal(data, &varChatInference200ResponseUsage)

	if err != nil {
		return err
	}

	*o = ChatInference200ResponseUsage(varChatInference200ResponseUsage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "inputTokens")
		delete(additionalProperties, "outputTokens")
		delete(additionalProperties, "totalTokens")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChatInference200ResponseUsage struct {
	value *ChatInference200ResponseUsage
	isSet bool
}

func (v NullableChatInference200ResponseUsage) Get() *ChatInference200ResponseUsage {
	return v.value
}

func (v *NullableChatInference200ResponseUsage) Set(val *ChatInference200ResponseUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableChatInference200ResponseUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableChatInference200ResponseUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatInference200ResponseUsage(val *ChatInference200ResponseUsage) *NullableChatInference200ResponseUsage {
	return &NullableChatInference200ResponseUsage{value: val, isSet: true}
}

func (v NullableChatInference200ResponseUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatInference200ResponseUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


