/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"time"
)

// checks if the ListFiles200ResponseFilesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListFiles200ResponseFilesInner{}

// ListFiles200ResponseFilesInner struct for ListFiles200ResponseFilesInner
type ListFiles200ResponseFilesInner struct {
	FileId *string `json:"fileId,omitempty"`
	Filename *string `json:"filename,omitempty"`
	ContentType *string `json:"contentType,omitempty"`
	Size *int32 `json:"size,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListFiles200ResponseFilesInner ListFiles200ResponseFilesInner

// NewListFiles200ResponseFilesInner instantiates a new ListFiles200ResponseFilesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListFiles200ResponseFilesInner() *ListFiles200ResponseFilesInner {
	this := ListFiles200ResponseFilesInner{}
	return &this
}

// NewListFiles200ResponseFilesInnerWithDefaults instantiates a new ListFiles200ResponseFilesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListFiles200ResponseFilesInnerWithDefaults() *ListFiles200ResponseFilesInner {
	this := ListFiles200ResponseFilesInner{}
	return &this
}

// GetFileId returns the FileId field value if set, zero value otherwise.
func (o *ListFiles200ResponseFilesInner) GetFileId() string {
	if o == nil || IsNil(o.FileId) {
		var ret string
		return ret
	}
	return *o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListFiles200ResponseFilesInner) GetFileIdOk() (*string, bool) {
	if o == nil || IsNil(o.FileId) {
		return nil, false
	}
	return o.FileId, true
}

// HasFileId returns a boolean if a field has been set.
func (o *ListFiles200ResponseFilesInner) HasFileId() bool {
	if o != nil && !IsNil(o.FileId) {
		return true
	}

	return false
}

// SetFileId gets a reference to the given string and assigns it to the FileId field.
func (o *ListFiles200ResponseFilesInner) SetFileId(v string) {
	o.FileId = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *ListFiles200ResponseFilesInner) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListFiles200ResponseFilesInner) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *ListFiles200ResponseFilesInner) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *ListFiles200ResponseFilesInner) SetFilename(v string) {
	o.Filename = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *ListFiles200ResponseFilesInner) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListFiles200ResponseFilesInner) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *ListFiles200ResponseFilesInner) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *ListFiles200ResponseFilesInner) SetContentType(v string) {
	o.ContentType = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ListFiles200ResponseFilesInner) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListFiles200ResponseFilesInner) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ListFiles200ResponseFilesInner) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *ListFiles200ResponseFilesInner) SetSize(v int32) {
	o.Size = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ListFiles200ResponseFilesInner) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListFiles200ResponseFilesInner) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ListFiles200ResponseFilesInner) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ListFiles200ResponseFilesInner) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ListFiles200ResponseFilesInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListFiles200ResponseFilesInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ListFiles200ResponseFilesInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ListFiles200ResponseFilesInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o ListFiles200ResponseFilesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListFiles200ResponseFilesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileId) {
		toSerialize["fileId"] = o.FileId
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.ContentType) {
		toSerialize["contentType"] = o.ContentType
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListFiles200ResponseFilesInner) UnmarshalJSON(data []byte) (err error) {
	varListFiles200ResponseFilesInner := _ListFiles200ResponseFilesInner{}

	err = json.Unmarshal(data, &varListFiles200ResponseFilesInner)

	if err != nil {
		return err
	}

	*o = ListFiles200ResponseFilesInner(varListFiles200ResponseFilesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fileId")
		delete(additionalProperties, "filename")
		delete(additionalProperties, "contentType")
		delete(additionalProperties, "size")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "createdAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListFiles200ResponseFilesInner struct {
	value *ListFiles200ResponseFilesInner
	isSet bool
}

func (v NullableListFiles200ResponseFilesInner) Get() *ListFiles200ResponseFilesInner {
	return v.value
}

func (v *NullableListFiles200ResponseFilesInner) Set(val *ListFiles200ResponseFilesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListFiles200ResponseFilesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListFiles200ResponseFilesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListFiles200ResponseFilesInner(val *ListFiles200ResponseFilesInner) *NullableListFiles200ResponseFilesInner {
	return &NullableListFiles200ResponseFilesInner{value: val, isSet: true}
}

func (v NullableListFiles200ResponseFilesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListFiles200ResponseFilesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


