/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkSetEnvironmentVariablesRequestEnvironmentInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkSetEnvironmentVariablesRequestEnvironmentInner{}

// BulkSetEnvironmentVariablesRequestEnvironmentInner struct for BulkSetEnvironmentVariablesRequestEnvironmentInner
type BulkSetEnvironmentVariablesRequestEnvironmentInner struct {
	Name string `json:"name"`
	Value string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _BulkSetEnvironmentVariablesRequestEnvironmentInner BulkSetEnvironmentVariablesRequestEnvironmentInner

// NewBulkSetEnvironmentVariablesRequestEnvironmentInner instantiates a new BulkSetEnvironmentVariablesRequestEnvironmentInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkSetEnvironmentVariablesRequestEnvironmentInner(name string, value string) *BulkSetEnvironmentVariablesRequestEnvironmentInner {
	this := BulkSetEnvironmentVariablesRequestEnvironmentInner{}
	this.Name = name
	this.Value = value
	return &this
}

// NewBulkSetEnvironmentVariablesRequestEnvironmentInnerWithDefaults instantiates a new BulkSetEnvironmentVariablesRequestEnvironmentInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkSetEnvironmentVariablesRequestEnvironmentInnerWithDefaults() *BulkSetEnvironmentVariablesRequestEnvironmentInner {
	this := BulkSetEnvironmentVariablesRequestEnvironmentInner{}
	return &this
}

// GetName returns the Name field value
func (o *BulkSetEnvironmentVariablesRequestEnvironmentInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BulkSetEnvironmentVariablesRequestEnvironmentInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BulkSetEnvironmentVariablesRequestEnvironmentInner) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *BulkSetEnvironmentVariablesRequestEnvironmentInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BulkSetEnvironmentVariablesRequestEnvironmentInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BulkSetEnvironmentVariablesRequestEnvironmentInner) SetValue(v string) {
	o.Value = v
}

func (o BulkSetEnvironmentVariablesRequestEnvironmentInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkSetEnvironmentVariablesRequestEnvironmentInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkSetEnvironmentVariablesRequestEnvironmentInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkSetEnvironmentVariablesRequestEnvironmentInner := _BulkSetEnvironmentVariablesRequestEnvironmentInner{}

	err = json.Unmarshal(data, &varBulkSetEnvironmentVariablesRequestEnvironmentInner)

	if err != nil {
		return err
	}

	*o = BulkSetEnvironmentVariablesRequestEnvironmentInner(varBulkSetEnvironmentVariablesRequestEnvironmentInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkSetEnvironmentVariablesRequestEnvironmentInner struct {
	value *BulkSetEnvironmentVariablesRequestEnvironmentInner
	isSet bool
}

func (v NullableBulkSetEnvironmentVariablesRequestEnvironmentInner) Get() *BulkSetEnvironmentVariablesRequestEnvironmentInner {
	return v.value
}

func (v *NullableBulkSetEnvironmentVariablesRequestEnvironmentInner) Set(val *BulkSetEnvironmentVariablesRequestEnvironmentInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkSetEnvironmentVariablesRequestEnvironmentInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkSetEnvironmentVariablesRequestEnvironmentInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkSetEnvironmentVariablesRequestEnvironmentInner(val *BulkSetEnvironmentVariablesRequestEnvironmentInner) *NullableBulkSetEnvironmentVariablesRequestEnvironmentInner {
	return &NullableBulkSetEnvironmentVariablesRequestEnvironmentInner{value: val, isSet: true}
}

func (v NullableBulkSetEnvironmentVariablesRequestEnvironmentInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkSetEnvironmentVariablesRequestEnvironmentInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


