/*
Quant administration API

The Quant administration API provides programmatic access to manage projects within your available organizations. 

API version: 2.0.0
Contact: apiteam@quantcdn.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OrganizationsOrganizationProjectsProjectGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsOrganizationProjectsProjectGet200Response{}

// OrganizationsOrganizationProjectsProjectGet200Response struct for OrganizationsOrganizationProjectsProjectGet200Response
type OrganizationsOrganizationProjectsProjectGet200Response struct {
	Data *OrganizationsOrganizationProjectsProjectGet200ResponseData `json:"data,omitempty"`
}

// NewOrganizationsOrganizationProjectsProjectGet200Response instantiates a new OrganizationsOrganizationProjectsProjectGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsOrganizationProjectsProjectGet200Response() *OrganizationsOrganizationProjectsProjectGet200Response {
	this := OrganizationsOrganizationProjectsProjectGet200Response{}
	return &this
}

// NewOrganizationsOrganizationProjectsProjectGet200ResponseWithDefaults instantiates a new OrganizationsOrganizationProjectsProjectGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsOrganizationProjectsProjectGet200ResponseWithDefaults() *OrganizationsOrganizationProjectsProjectGet200Response {
	this := OrganizationsOrganizationProjectsProjectGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OrganizationsOrganizationProjectsProjectGet200Response) GetData() OrganizationsOrganizationProjectsProjectGet200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret OrganizationsOrganizationProjectsProjectGet200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsOrganizationProjectsProjectGet200Response) GetDataOk() (*OrganizationsOrganizationProjectsProjectGet200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OrganizationsOrganizationProjectsProjectGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given OrganizationsOrganizationProjectsProjectGet200ResponseData and assigns it to the Data field.
func (o *OrganizationsOrganizationProjectsProjectGet200Response) SetData(v OrganizationsOrganizationProjectsProjectGet200ResponseData) {
	o.Data = &v
}

func (o OrganizationsOrganizationProjectsProjectGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsOrganizationProjectsProjectGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableOrganizationsOrganizationProjectsProjectGet200Response struct {
	value *OrganizationsOrganizationProjectsProjectGet200Response
	isSet bool
}

func (v NullableOrganizationsOrganizationProjectsProjectGet200Response) Get() *OrganizationsOrganizationProjectsProjectGet200Response {
	return v.value
}

func (v *NullableOrganizationsOrganizationProjectsProjectGet200Response) Set(val *OrganizationsOrganizationProjectsProjectGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsOrganizationProjectsProjectGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsOrganizationProjectsProjectGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsOrganizationProjectsProjectGet200Response(val *OrganizationsOrganizationProjectsProjectGet200Response) *NullableOrganizationsOrganizationProjectsProjectGet200Response {
	return &NullableOrganizationsOrganizationProjectsProjectGet200Response{value: val, isSet: true}
}

func (v NullableOrganizationsOrganizationProjectsProjectGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsOrganizationProjectsProjectGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


