/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
)

// checks if the UpdateAIAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAIAgentRequest{}

// UpdateAIAgentRequest struct for UpdateAIAgentRequest
type UpdateAIAgentRequest struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Group *string `json:"group,omitempty"`
	SystemPrompt *string `json:"systemPrompt,omitempty"`
	Temperature *float32 `json:"temperature,omitempty"`
	ModelId *string `json:"modelId,omitempty"`
	MaxTokens *int32 `json:"maxTokens,omitempty"`
	AllowedTools []string `json:"allowedTools,omitempty"`
	AllowedCollections []string `json:"allowedCollections,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAIAgentRequest UpdateAIAgentRequest

// NewUpdateAIAgentRequest instantiates a new UpdateAIAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAIAgentRequest() *UpdateAIAgentRequest {
	this := UpdateAIAgentRequest{}
	return &this
}

// NewUpdateAIAgentRequestWithDefaults instantiates a new UpdateAIAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAIAgentRequestWithDefaults() *UpdateAIAgentRequest {
	this := UpdateAIAgentRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateAIAgentRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAIAgentRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateAIAgentRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateAIAgentRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateAIAgentRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAIAgentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateAIAgentRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateAIAgentRequest) SetDescription(v string) {
	o.Description = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *UpdateAIAgentRequest) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAIAgentRequest) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *UpdateAIAgentRequest) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *UpdateAIAgentRequest) SetGroup(v string) {
	o.Group = &v
}

// GetSystemPrompt returns the SystemPrompt field value if set, zero value otherwise.
func (o *UpdateAIAgentRequest) GetSystemPrompt() string {
	if o == nil || IsNil(o.SystemPrompt) {
		var ret string
		return ret
	}
	return *o.SystemPrompt
}

// GetSystemPromptOk returns a tuple with the SystemPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAIAgentRequest) GetSystemPromptOk() (*string, bool) {
	if o == nil || IsNil(o.SystemPrompt) {
		return nil, false
	}
	return o.SystemPrompt, true
}

// HasSystemPrompt returns a boolean if a field has been set.
func (o *UpdateAIAgentRequest) HasSystemPrompt() bool {
	if o != nil && !IsNil(o.SystemPrompt) {
		return true
	}

	return false
}

// SetSystemPrompt gets a reference to the given string and assigns it to the SystemPrompt field.
func (o *UpdateAIAgentRequest) SetSystemPrompt(v string) {
	o.SystemPrompt = &v
}

// GetTemperature returns the Temperature field value if set, zero value otherwise.
func (o *UpdateAIAgentRequest) GetTemperature() float32 {
	if o == nil || IsNil(o.Temperature) {
		var ret float32
		return ret
	}
	return *o.Temperature
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAIAgentRequest) GetTemperatureOk() (*float32, bool) {
	if o == nil || IsNil(o.Temperature) {
		return nil, false
	}
	return o.Temperature, true
}

// HasTemperature returns a boolean if a field has been set.
func (o *UpdateAIAgentRequest) HasTemperature() bool {
	if o != nil && !IsNil(o.Temperature) {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given float32 and assigns it to the Temperature field.
func (o *UpdateAIAgentRequest) SetTemperature(v float32) {
	o.Temperature = &v
}

// GetModelId returns the ModelId field value if set, zero value otherwise.
func (o *UpdateAIAgentRequest) GetModelId() string {
	if o == nil || IsNil(o.ModelId) {
		var ret string
		return ret
	}
	return *o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAIAgentRequest) GetModelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ModelId) {
		return nil, false
	}
	return o.ModelId, true
}

// HasModelId returns a boolean if a field has been set.
func (o *UpdateAIAgentRequest) HasModelId() bool {
	if o != nil && !IsNil(o.ModelId) {
		return true
	}

	return false
}

// SetModelId gets a reference to the given string and assigns it to the ModelId field.
func (o *UpdateAIAgentRequest) SetModelId(v string) {
	o.ModelId = &v
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *UpdateAIAgentRequest) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret int32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAIAgentRequest) GetMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *UpdateAIAgentRequest) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given int32 and assigns it to the MaxTokens field.
func (o *UpdateAIAgentRequest) SetMaxTokens(v int32) {
	o.MaxTokens = &v
}

// GetAllowedTools returns the AllowedTools field value if set, zero value otherwise.
func (o *UpdateAIAgentRequest) GetAllowedTools() []string {
	if o == nil || IsNil(o.AllowedTools) {
		var ret []string
		return ret
	}
	return o.AllowedTools
}

// GetAllowedToolsOk returns a tuple with the AllowedTools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAIAgentRequest) GetAllowedToolsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedTools) {
		return nil, false
	}
	return o.AllowedTools, true
}

// HasAllowedTools returns a boolean if a field has been set.
func (o *UpdateAIAgentRequest) HasAllowedTools() bool {
	if o != nil && !IsNil(o.AllowedTools) {
		return true
	}

	return false
}

// SetAllowedTools gets a reference to the given []string and assigns it to the AllowedTools field.
func (o *UpdateAIAgentRequest) SetAllowedTools(v []string) {
	o.AllowedTools = v
}

// GetAllowedCollections returns the AllowedCollections field value if set, zero value otherwise.
func (o *UpdateAIAgentRequest) GetAllowedCollections() []string {
	if o == nil || IsNil(o.AllowedCollections) {
		var ret []string
		return ret
	}
	return o.AllowedCollections
}

// GetAllowedCollectionsOk returns a tuple with the AllowedCollections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAIAgentRequest) GetAllowedCollectionsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedCollections) {
		return nil, false
	}
	return o.AllowedCollections, true
}

// HasAllowedCollections returns a boolean if a field has been set.
func (o *UpdateAIAgentRequest) HasAllowedCollections() bool {
	if o != nil && !IsNil(o.AllowedCollections) {
		return true
	}

	return false
}

// SetAllowedCollections gets a reference to the given []string and assigns it to the AllowedCollections field.
func (o *UpdateAIAgentRequest) SetAllowedCollections(v []string) {
	o.AllowedCollections = v
}

func (o UpdateAIAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAIAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.SystemPrompt) {
		toSerialize["systemPrompt"] = o.SystemPrompt
	}
	if !IsNil(o.Temperature) {
		toSerialize["temperature"] = o.Temperature
	}
	if !IsNil(o.ModelId) {
		toSerialize["modelId"] = o.ModelId
	}
	if !IsNil(o.MaxTokens) {
		toSerialize["maxTokens"] = o.MaxTokens
	}
	if !IsNil(o.AllowedTools) {
		toSerialize["allowedTools"] = o.AllowedTools
	}
	if !IsNil(o.AllowedCollections) {
		toSerialize["allowedCollections"] = o.AllowedCollections
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAIAgentRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateAIAgentRequest := _UpdateAIAgentRequest{}

	err = json.Unmarshal(data, &varUpdateAIAgentRequest)

	if err != nil {
		return err
	}

	*o = UpdateAIAgentRequest(varUpdateAIAgentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "group")
		delete(additionalProperties, "systemPrompt")
		delete(additionalProperties, "temperature")
		delete(additionalProperties, "modelId")
		delete(additionalProperties, "maxTokens")
		delete(additionalProperties, "allowedTools")
		delete(additionalProperties, "allowedCollections")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAIAgentRequest struct {
	value *UpdateAIAgentRequest
	isSet bool
}

func (v NullableUpdateAIAgentRequest) Get() *UpdateAIAgentRequest {
	return v.value
}

func (v *NullableUpdateAIAgentRequest) Set(val *UpdateAIAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAIAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAIAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAIAgentRequest(val *UpdateAIAgentRequest) *NullableUpdateAIAgentRequest {
	return &NullableUpdateAIAgentRequest{value: val, isSet: true}
}

func (v NullableUpdateAIAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAIAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


