/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.17.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
)

// checks if the GetAgentOverlay200ResponseBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAgentOverlay200ResponseBase{}

// GetAgentOverlay200ResponseBase Base global agent metadata
type GetAgentOverlay200ResponseBase struct {
	AgentId *string `json:"agentId,omitempty"`
	Name *string `json:"name,omitempty"`
	ModelId *string `json:"modelId,omitempty"`
	AllowedTools []string `json:"allowedTools,omitempty"`
	AssignedSkillIds []string `json:"assignedSkillIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAgentOverlay200ResponseBase GetAgentOverlay200ResponseBase

// NewGetAgentOverlay200ResponseBase instantiates a new GetAgentOverlay200ResponseBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAgentOverlay200ResponseBase() *GetAgentOverlay200ResponseBase {
	this := GetAgentOverlay200ResponseBase{}
	return &this
}

// NewGetAgentOverlay200ResponseBaseWithDefaults instantiates a new GetAgentOverlay200ResponseBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAgentOverlay200ResponseBaseWithDefaults() *GetAgentOverlay200ResponseBase {
	this := GetAgentOverlay200ResponseBase{}
	return &this
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *GetAgentOverlay200ResponseBase) GetAgentId() string {
	if o == nil || IsNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAgentOverlay200ResponseBase) GetAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *GetAgentOverlay200ResponseBase) HasAgentId() bool {
	if o != nil && !IsNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *GetAgentOverlay200ResponseBase) SetAgentId(v string) {
	o.AgentId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetAgentOverlay200ResponseBase) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAgentOverlay200ResponseBase) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetAgentOverlay200ResponseBase) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetAgentOverlay200ResponseBase) SetName(v string) {
	o.Name = &v
}

// GetModelId returns the ModelId field value if set, zero value otherwise.
func (o *GetAgentOverlay200ResponseBase) GetModelId() string {
	if o == nil || IsNil(o.ModelId) {
		var ret string
		return ret
	}
	return *o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAgentOverlay200ResponseBase) GetModelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ModelId) {
		return nil, false
	}
	return o.ModelId, true
}

// HasModelId returns a boolean if a field has been set.
func (o *GetAgentOverlay200ResponseBase) HasModelId() bool {
	if o != nil && !IsNil(o.ModelId) {
		return true
	}

	return false
}

// SetModelId gets a reference to the given string and assigns it to the ModelId field.
func (o *GetAgentOverlay200ResponseBase) SetModelId(v string) {
	o.ModelId = &v
}

// GetAllowedTools returns the AllowedTools field value if set, zero value otherwise.
func (o *GetAgentOverlay200ResponseBase) GetAllowedTools() []string {
	if o == nil || IsNil(o.AllowedTools) {
		var ret []string
		return ret
	}
	return o.AllowedTools
}

// GetAllowedToolsOk returns a tuple with the AllowedTools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAgentOverlay200ResponseBase) GetAllowedToolsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedTools) {
		return nil, false
	}
	return o.AllowedTools, true
}

// HasAllowedTools returns a boolean if a field has been set.
func (o *GetAgentOverlay200ResponseBase) HasAllowedTools() bool {
	if o != nil && !IsNil(o.AllowedTools) {
		return true
	}

	return false
}

// SetAllowedTools gets a reference to the given []string and assigns it to the AllowedTools field.
func (o *GetAgentOverlay200ResponseBase) SetAllowedTools(v []string) {
	o.AllowedTools = v
}

// GetAssignedSkillIds returns the AssignedSkillIds field value if set, zero value otherwise.
func (o *GetAgentOverlay200ResponseBase) GetAssignedSkillIds() []string {
	if o == nil || IsNil(o.AssignedSkillIds) {
		var ret []string
		return ret
	}
	return o.AssignedSkillIds
}

// GetAssignedSkillIdsOk returns a tuple with the AssignedSkillIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAgentOverlay200ResponseBase) GetAssignedSkillIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AssignedSkillIds) {
		return nil, false
	}
	return o.AssignedSkillIds, true
}

// HasAssignedSkillIds returns a boolean if a field has been set.
func (o *GetAgentOverlay200ResponseBase) HasAssignedSkillIds() bool {
	if o != nil && !IsNil(o.AssignedSkillIds) {
		return true
	}

	return false
}

// SetAssignedSkillIds gets a reference to the given []string and assigns it to the AssignedSkillIds field.
func (o *GetAgentOverlay200ResponseBase) SetAssignedSkillIds(v []string) {
	o.AssignedSkillIds = v
}

func (o GetAgentOverlay200ResponseBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAgentOverlay200ResponseBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentId) {
		toSerialize["agentId"] = o.AgentId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ModelId) {
		toSerialize["modelId"] = o.ModelId
	}
	if !IsNil(o.AllowedTools) {
		toSerialize["allowedTools"] = o.AllowedTools
	}
	if !IsNil(o.AssignedSkillIds) {
		toSerialize["assignedSkillIds"] = o.AssignedSkillIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAgentOverlay200ResponseBase) UnmarshalJSON(data []byte) (err error) {
	varGetAgentOverlay200ResponseBase := _GetAgentOverlay200ResponseBase{}

	err = json.Unmarshal(data, &varGetAgentOverlay200ResponseBase)

	if err != nil {
		return err
	}

	*o = GetAgentOverlay200ResponseBase(varGetAgentOverlay200ResponseBase)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "agentId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "modelId")
		delete(additionalProperties, "allowedTools")
		delete(additionalProperties, "assignedSkillIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAgentOverlay200ResponseBase struct {
	value *GetAgentOverlay200ResponseBase
	isSet bool
}

func (v NullableGetAgentOverlay200ResponseBase) Get() *GetAgentOverlay200ResponseBase {
	return v.value
}

func (v *NullableGetAgentOverlay200ResponseBase) Set(val *GetAgentOverlay200ResponseBase) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAgentOverlay200ResponseBase) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAgentOverlay200ResponseBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAgentOverlay200ResponseBase(val *GetAgentOverlay200ResponseBase) *NullableGetAgentOverlay200ResponseBase {
	return &NullableGetAgentOverlay200ResponseBase{value: val, isSet: true}
}

func (v NullableGetAgentOverlay200ResponseBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAgentOverlay200ResponseBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


