/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.24.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"fmt"
)

// checks if the PurgeOrgResourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurgeOrgResourceRequest{}

// PurgeOrgResourceRequest struct for PurgeOrgResourceRequest
type PurgeOrgResourceRequest struct {
	Scope string `json:"scope"`
	// scope environment only
	Application *string `json:"application,omitempty"`
	// scope environment only
	Environment *string `json:"environment,omitempty"`
	// scope all only; must be true
	Confirm *bool `json:"confirm,omitempty"`
	// scope environment only; resume a partial purge
	Cursor *string `json:"cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PurgeOrgResourceRequest PurgeOrgResourceRequest

// NewPurgeOrgResourceRequest instantiates a new PurgeOrgResourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurgeOrgResourceRequest(scope string) *PurgeOrgResourceRequest {
	this := PurgeOrgResourceRequest{}
	this.Scope = scope
	return &this
}

// NewPurgeOrgResourceRequestWithDefaults instantiates a new PurgeOrgResourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurgeOrgResourceRequestWithDefaults() *PurgeOrgResourceRequest {
	this := PurgeOrgResourceRequest{}
	return &this
}

// GetScope returns the Scope field value
func (o *PurgeOrgResourceRequest) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *PurgeOrgResourceRequest) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *PurgeOrgResourceRequest) SetScope(v string) {
	o.Scope = v
}

// GetApplication returns the Application field value if set, zero value otherwise.
func (o *PurgeOrgResourceRequest) GetApplication() string {
	if o == nil || IsNil(o.Application) {
		var ret string
		return ret
	}
	return *o.Application
}

// GetApplicationOk returns a tuple with the Application field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurgeOrgResourceRequest) GetApplicationOk() (*string, bool) {
	if o == nil || IsNil(o.Application) {
		return nil, false
	}
	return o.Application, true
}

// HasApplication returns a boolean if a field has been set.
func (o *PurgeOrgResourceRequest) HasApplication() bool {
	if o != nil && !IsNil(o.Application) {
		return true
	}

	return false
}

// SetApplication gets a reference to the given string and assigns it to the Application field.
func (o *PurgeOrgResourceRequest) SetApplication(v string) {
	o.Application = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *PurgeOrgResourceRequest) GetEnvironment() string {
	if o == nil || IsNil(o.Environment) {
		var ret string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurgeOrgResourceRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *PurgeOrgResourceRequest) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given string and assigns it to the Environment field.
func (o *PurgeOrgResourceRequest) SetEnvironment(v string) {
	o.Environment = &v
}

// GetConfirm returns the Confirm field value if set, zero value otherwise.
func (o *PurgeOrgResourceRequest) GetConfirm() bool {
	if o == nil || IsNil(o.Confirm) {
		var ret bool
		return ret
	}
	return *o.Confirm
}

// GetConfirmOk returns a tuple with the Confirm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurgeOrgResourceRequest) GetConfirmOk() (*bool, bool) {
	if o == nil || IsNil(o.Confirm) {
		return nil, false
	}
	return o.Confirm, true
}

// HasConfirm returns a boolean if a field has been set.
func (o *PurgeOrgResourceRequest) HasConfirm() bool {
	if o != nil && !IsNil(o.Confirm) {
		return true
	}

	return false
}

// SetConfirm gets a reference to the given bool and assigns it to the Confirm field.
func (o *PurgeOrgResourceRequest) SetConfirm(v bool) {
	o.Confirm = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *PurgeOrgResourceRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurgeOrgResourceRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *PurgeOrgResourceRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *PurgeOrgResourceRequest) SetCursor(v string) {
	o.Cursor = &v
}

func (o PurgeOrgResourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurgeOrgResourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scope"] = o.Scope
	if !IsNil(o.Application) {
		toSerialize["application"] = o.Application
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.Confirm) {
		toSerialize["confirm"] = o.Confirm
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PurgeOrgResourceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPurgeOrgResourceRequest := _PurgeOrgResourceRequest{}

	err = json.Unmarshal(data, &varPurgeOrgResourceRequest)

	if err != nil {
		return err
	}

	*o = PurgeOrgResourceRequest(varPurgeOrgResourceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "scope")
		delete(additionalProperties, "application")
		delete(additionalProperties, "environment")
		delete(additionalProperties, "confirm")
		delete(additionalProperties, "cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePurgeOrgResourceRequest struct {
	value *PurgeOrgResourceRequest
	isSet bool
}

func (v NullablePurgeOrgResourceRequest) Get() *PurgeOrgResourceRequest {
	return v.value
}

func (v *NullablePurgeOrgResourceRequest) Set(val *PurgeOrgResourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePurgeOrgResourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePurgeOrgResourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurgeOrgResourceRequest(val *PurgeOrgResourceRequest) *NullablePurgeOrgResourceRequest {
	return &NullablePurgeOrgResourceRequest{value: val, isSet: true}
}

func (v NullablePurgeOrgResourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurgeOrgResourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


