/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"time"
)

// checks if the ListBackups200ResponseBackupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBackups200ResponseBackupsInner{}

// ListBackups200ResponseBackupsInner struct for ListBackups200ResponseBackupsInner
type ListBackups200ResponseBackupsInner struct {
	BackupId *string `json:"backupId,omitempty"`
	Status *string `json:"status,omitempty"`
	Type *string `json:"type,omitempty"`
	Engine *string `json:"engine,omitempty"`
	Description *string `json:"description,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	TaskArn *string `json:"taskArn,omitempty"`
	S3Key *string `json:"s3Key,omitempty"`
	BucketName *string `json:"bucketName,omitempty"`
	Size *int32 `json:"size,omitempty"`
	SizeFormatted *string `json:"sizeFormatted,omitempty"`
	FileExists *bool `json:"fileExists,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListBackups200ResponseBackupsInner ListBackups200ResponseBackupsInner

// NewListBackups200ResponseBackupsInner instantiates a new ListBackups200ResponseBackupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBackups200ResponseBackupsInner() *ListBackups200ResponseBackupsInner {
	this := ListBackups200ResponseBackupsInner{}
	return &this
}

// NewListBackups200ResponseBackupsInnerWithDefaults instantiates a new ListBackups200ResponseBackupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBackups200ResponseBackupsInnerWithDefaults() *ListBackups200ResponseBackupsInner {
	this := ListBackups200ResponseBackupsInner{}
	return &this
}

// GetBackupId returns the BackupId field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetBackupId() string {
	if o == nil || IsNil(o.BackupId) {
		var ret string
		return ret
	}
	return *o.BackupId
}

// GetBackupIdOk returns a tuple with the BackupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetBackupIdOk() (*string, bool) {
	if o == nil || IsNil(o.BackupId) {
		return nil, false
	}
	return o.BackupId, true
}

// HasBackupId returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasBackupId() bool {
	if o != nil && !IsNil(o.BackupId) {
		return true
	}

	return false
}

// SetBackupId gets a reference to the given string and assigns it to the BackupId field.
func (o *ListBackups200ResponseBackupsInner) SetBackupId(v string) {
	o.BackupId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ListBackups200ResponseBackupsInner) SetStatus(v string) {
	o.Status = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ListBackups200ResponseBackupsInner) SetType(v string) {
	o.Type = &v
}

// GetEngine returns the Engine field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetEngine() string {
	if o == nil || IsNil(o.Engine) {
		var ret string
		return ret
	}
	return *o.Engine
}

// GetEngineOk returns a tuple with the Engine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetEngineOk() (*string, bool) {
	if o == nil || IsNil(o.Engine) {
		return nil, false
	}
	return o.Engine, true
}

// HasEngine returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasEngine() bool {
	if o != nil && !IsNil(o.Engine) {
		return true
	}

	return false
}

// SetEngine gets a reference to the given string and assigns it to the Engine field.
func (o *ListBackups200ResponseBackupsInner) SetEngine(v string) {
	o.Engine = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ListBackups200ResponseBackupsInner) SetDescription(v string) {
	o.Description = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ListBackups200ResponseBackupsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ListBackups200ResponseBackupsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetTaskArn returns the TaskArn field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetTaskArn() string {
	if o == nil || IsNil(o.TaskArn) {
		var ret string
		return ret
	}
	return *o.TaskArn
}

// GetTaskArnOk returns a tuple with the TaskArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetTaskArnOk() (*string, bool) {
	if o == nil || IsNil(o.TaskArn) {
		return nil, false
	}
	return o.TaskArn, true
}

// HasTaskArn returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasTaskArn() bool {
	if o != nil && !IsNil(o.TaskArn) {
		return true
	}

	return false
}

// SetTaskArn gets a reference to the given string and assigns it to the TaskArn field.
func (o *ListBackups200ResponseBackupsInner) SetTaskArn(v string) {
	o.TaskArn = &v
}

// GetS3Key returns the S3Key field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetS3Key() string {
	if o == nil || IsNil(o.S3Key) {
		var ret string
		return ret
	}
	return *o.S3Key
}

// GetS3KeyOk returns a tuple with the S3Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetS3KeyOk() (*string, bool) {
	if o == nil || IsNil(o.S3Key) {
		return nil, false
	}
	return o.S3Key, true
}

// HasS3Key returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasS3Key() bool {
	if o != nil && !IsNil(o.S3Key) {
		return true
	}

	return false
}

// SetS3Key gets a reference to the given string and assigns it to the S3Key field.
func (o *ListBackups200ResponseBackupsInner) SetS3Key(v string) {
	o.S3Key = &v
}

// GetBucketName returns the BucketName field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetBucketName() string {
	if o == nil || IsNil(o.BucketName) {
		var ret string
		return ret
	}
	return *o.BucketName
}

// GetBucketNameOk returns a tuple with the BucketName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetBucketNameOk() (*string, bool) {
	if o == nil || IsNil(o.BucketName) {
		return nil, false
	}
	return o.BucketName, true
}

// HasBucketName returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasBucketName() bool {
	if o != nil && !IsNil(o.BucketName) {
		return true
	}

	return false
}

// SetBucketName gets a reference to the given string and assigns it to the BucketName field.
func (o *ListBackups200ResponseBackupsInner) SetBucketName(v string) {
	o.BucketName = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *ListBackups200ResponseBackupsInner) SetSize(v int32) {
	o.Size = &v
}

// GetSizeFormatted returns the SizeFormatted field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetSizeFormatted() string {
	if o == nil || IsNil(o.SizeFormatted) {
		var ret string
		return ret
	}
	return *o.SizeFormatted
}

// GetSizeFormattedOk returns a tuple with the SizeFormatted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetSizeFormattedOk() (*string, bool) {
	if o == nil || IsNil(o.SizeFormatted) {
		return nil, false
	}
	return o.SizeFormatted, true
}

// HasSizeFormatted returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasSizeFormatted() bool {
	if o != nil && !IsNil(o.SizeFormatted) {
		return true
	}

	return false
}

// SetSizeFormatted gets a reference to the given string and assigns it to the SizeFormatted field.
func (o *ListBackups200ResponseBackupsInner) SetSizeFormatted(v string) {
	o.SizeFormatted = &v
}

// GetFileExists returns the FileExists field value if set, zero value otherwise.
func (o *ListBackups200ResponseBackupsInner) GetFileExists() bool {
	if o == nil || IsNil(o.FileExists) {
		var ret bool
		return ret
	}
	return *o.FileExists
}

// GetFileExistsOk returns a tuple with the FileExists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackups200ResponseBackupsInner) GetFileExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.FileExists) {
		return nil, false
	}
	return o.FileExists, true
}

// HasFileExists returns a boolean if a field has been set.
func (o *ListBackups200ResponseBackupsInner) HasFileExists() bool {
	if o != nil && !IsNil(o.FileExists) {
		return true
	}

	return false
}

// SetFileExists gets a reference to the given bool and assigns it to the FileExists field.
func (o *ListBackups200ResponseBackupsInner) SetFileExists(v bool) {
	o.FileExists = &v
}

func (o ListBackups200ResponseBackupsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBackups200ResponseBackupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BackupId) {
		toSerialize["backupId"] = o.BackupId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Engine) {
		toSerialize["engine"] = o.Engine
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.TaskArn) {
		toSerialize["taskArn"] = o.TaskArn
	}
	if !IsNil(o.S3Key) {
		toSerialize["s3Key"] = o.S3Key
	}
	if !IsNil(o.BucketName) {
		toSerialize["bucketName"] = o.BucketName
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.SizeFormatted) {
		toSerialize["sizeFormatted"] = o.SizeFormatted
	}
	if !IsNil(o.FileExists) {
		toSerialize["fileExists"] = o.FileExists
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListBackups200ResponseBackupsInner) UnmarshalJSON(data []byte) (err error) {
	varListBackups200ResponseBackupsInner := _ListBackups200ResponseBackupsInner{}

	err = json.Unmarshal(data, &varListBackups200ResponseBackupsInner)

	if err != nil {
		return err
	}

	*o = ListBackups200ResponseBackupsInner(varListBackups200ResponseBackupsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "backupId")
		delete(additionalProperties, "status")
		delete(additionalProperties, "type")
		delete(additionalProperties, "engine")
		delete(additionalProperties, "description")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "taskArn")
		delete(additionalProperties, "s3Key")
		delete(additionalProperties, "bucketName")
		delete(additionalProperties, "size")
		delete(additionalProperties, "sizeFormatted")
		delete(additionalProperties, "fileExists")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListBackups200ResponseBackupsInner struct {
	value *ListBackups200ResponseBackupsInner
	isSet bool
}

func (v NullableListBackups200ResponseBackupsInner) Get() *ListBackups200ResponseBackupsInner {
	return v.value
}

func (v *NullableListBackups200ResponseBackupsInner) Set(val *ListBackups200ResponseBackupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListBackups200ResponseBackupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListBackups200ResponseBackupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBackups200ResponseBackupsInner(val *ListBackups200ResponseBackupsInner) *NullableListBackups200ResponseBackupsInner {
	return &NullableListBackups200ResponseBackupsInner{value: val, isSet: true}
}

func (v NullableListBackups200ResponseBackupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBackups200ResponseBackupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


