/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"fmt"
)

// checks if the V2RuleAuthRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2RuleAuthRequest{}

// V2RuleAuthRequest struct for V2RuleAuthRequest
type V2RuleAuthRequest struct {
	// Error message
	Message string `json:"message"`
	// Error flag
	Error bool `json:"error"`
	// Domain patterns (default: any)
	Domain []string `json:"domain"`
	// Rule name
	Name *string `json:"name,omitempty"`
	// Rule UUID
	Uuid *string `json:"uuid,omitempty"`
	// Rule weight
	Weight *int32 `json:"weight,omitempty"`
	// Whether rule is disabled
	Disabled *bool `json:"disabled,omitempty"`
	// URL patterns
	Url []string `json:"url"`
	// Country filter type (country_is, country_is_not, any)
	Country *string `json:"country,omitempty"`
	// Allowed countries
	CountryIs []string `json:"country_is,omitempty"`
	// Excluded countries
	CountryIsNot []string `json:"country_is_not,omitempty"`
	// Method filter type (method_is, method_is_not, any)
	Method *string `json:"method,omitempty"`
	// Allowed HTTP methods
	MethodIs []string `json:"method_is,omitempty"`
	// Excluded HTTP methods
	MethodIsNot []string `json:"method_is_not,omitempty"`
	// IP filter type (ip_is, ip_is_not, any)
	Ip *string `json:"ip,omitempty"`
	// Allowed IP addresses
	IpIs []string `json:"ip_is,omitempty"`
	// Excluded IP addresses
	IpIsNot []string `json:"ip_is_not,omitempty"`
	// Target URL to proxy to
	To string `json:"to"`
	// Host header override
	Host *string `json:"host,omitempty"`
	// Authentication username
	AuthUser string `json:"auth_user"`
	// Authentication password
	AuthPass string `json:"auth_pass"`
	// Disable SSL verification
	DisableSslVerify *bool `json:"disable_ssl_verify,omitempty"`
	// Cache lifetime
	CacheLifetime NullableString `json:"cache_lifetime,omitempty"`
	// Only proxy 404 responses
	OnlyProxy404 *bool `json:"only_proxy_404,omitempty"`
	// Headers to inject
	InjectHeaders map[string]string `json:"inject_headers,omitempty"`
	// Headers to strip from response
	ProxyStripHeaders []string `json:"proxy_strip_headers,omitempty"`
	// Headers to strip from request
	ProxyStripRequestHeaders []string `json:"proxy_strip_request_headers,omitempty"`
	// Origin timeout
	OriginTimeout *string `json:"origin_timeout,omitempty"`
	// Enable failover mode
	FailoverMode *bool `json:"failover_mode,omitempty"`
	// Failover TTFB threshold
	FailoverOriginTtfb *string `json:"failover_origin_ttfb,omitempty"`
	// Status codes for failover (default: 200,404,301,302,304)
	FailoverOriginStatusCodes []string `json:"failover_origin_status_codes,omitempty"`
	// Failover cache lifetime
	FailoverLifetime *string `json:"failover_lifetime,omitempty"`
	// Notification type (none, slack)
	Notify *string `json:"notify,omitempty"`
	NotifyConfig NullableV2RuleProxyActionAllOfNotifyConfig `json:"notify_config,omitempty"`
	// WAF enabled
	WafEnabled *bool `json:"waf_enabled,omitempty"`
	WafConfig *WafConfig `json:"waf_config,omitempty"`
	// Proxy alert enabled
	ProxyAlertEnabled *bool `json:"proxy_alert_enabled,omitempty"`
	// Proxy inline function enabled
	ProxyInlineFnEnabled *bool `json:"proxy_inline_fn_enabled,omitempty"`
	QuantCloudSelection NullableV2RuleProxyActionAllOfQuantCloudSelection `json:"quant_cloud_selection,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V2RuleAuthRequest V2RuleAuthRequest

// NewV2RuleAuthRequest instantiates a new V2RuleAuthRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2RuleAuthRequest(message string, error_ bool, domain []string, url []string, to string, authUser string, authPass string) *V2RuleAuthRequest {
	this := V2RuleAuthRequest{}
	this.Message = message
	this.Error = error_
	this.Domain = domain
	var weight int32 = 0
	this.Weight = &weight
	var disabled bool = false
	this.Disabled = &disabled
	this.Url = url
	this.To = to
	this.AuthUser = authUser
	this.AuthPass = authPass
	var disableSslVerify bool = false
	this.DisableSslVerify = &disableSslVerify
	var onlyProxy404 bool = false
	this.OnlyProxy404 = &onlyProxy404
	var failoverMode bool = false
	this.FailoverMode = &failoverMode
	var failoverOriginTtfb string = "2000"
	this.FailoverOriginTtfb = &failoverOriginTtfb
	var failoverLifetime string = "300"
	this.FailoverLifetime = &failoverLifetime
	var notify string = "none"
	this.Notify = &notify
	var wafEnabled bool = false
	this.WafEnabled = &wafEnabled
	var proxyInlineFnEnabled bool = false
	this.ProxyInlineFnEnabled = &proxyInlineFnEnabled
	return &this
}

// NewV2RuleAuthRequestWithDefaults instantiates a new V2RuleAuthRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2RuleAuthRequestWithDefaults() *V2RuleAuthRequest {
	this := V2RuleAuthRequest{}
	var weight int32 = 0
	this.Weight = &weight
	var disabled bool = false
	this.Disabled = &disabled
	var disableSslVerify bool = false
	this.DisableSslVerify = &disableSslVerify
	var onlyProxy404 bool = false
	this.OnlyProxy404 = &onlyProxy404
	var failoverMode bool = false
	this.FailoverMode = &failoverMode
	var failoverOriginTtfb string = "2000"
	this.FailoverOriginTtfb = &failoverOriginTtfb
	var failoverLifetime string = "300"
	this.FailoverLifetime = &failoverLifetime
	var notify string = "none"
	this.Notify = &notify
	var wafEnabled bool = false
	this.WafEnabled = &wafEnabled
	var proxyInlineFnEnabled bool = false
	this.ProxyInlineFnEnabled = &proxyInlineFnEnabled
	return &this
}

// GetMessage returns the Message field value
func (o *V2RuleAuthRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *V2RuleAuthRequest) SetMessage(v string) {
	o.Message = v
}

// GetError returns the Error field value
func (o *V2RuleAuthRequest) GetError() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetErrorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *V2RuleAuthRequest) SetError(v bool) {
	o.Error = v
}

// GetDomain returns the Domain field value
func (o *V2RuleAuthRequest) GetDomain() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetDomainOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domain, true
}

// SetDomain sets field value
func (o *V2RuleAuthRequest) SetDomain(v []string) {
	o.Domain = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V2RuleAuthRequest) SetName(v string) {
	o.Name = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *V2RuleAuthRequest) SetUuid(v string) {
	o.Uuid = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetWeight() int32 {
	if o == nil || IsNil(o.Weight) {
		var ret int32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetWeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given int32 and assigns it to the Weight field.
func (o *V2RuleAuthRequest) SetWeight(v int32) {
	o.Weight = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *V2RuleAuthRequest) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetUrl returns the Url field value
func (o *V2RuleAuthRequest) GetUrl() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetUrlOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url, true
}

// SetUrl sets field value
func (o *V2RuleAuthRequest) SetUrl(v []string) {
	o.Url = v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *V2RuleAuthRequest) SetCountry(v string) {
	o.Country = &v
}

// GetCountryIs returns the CountryIs field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetCountryIs() []string {
	if o == nil || IsNil(o.CountryIs) {
		var ret []string
		return ret
	}
	return o.CountryIs
}

// GetCountryIsOk returns a tuple with the CountryIs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetCountryIsOk() ([]string, bool) {
	if o == nil || IsNil(o.CountryIs) {
		return nil, false
	}
	return o.CountryIs, true
}

// HasCountryIs returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasCountryIs() bool {
	if o != nil && !IsNil(o.CountryIs) {
		return true
	}

	return false
}

// SetCountryIs gets a reference to the given []string and assigns it to the CountryIs field.
func (o *V2RuleAuthRequest) SetCountryIs(v []string) {
	o.CountryIs = v
}

// GetCountryIsNot returns the CountryIsNot field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetCountryIsNot() []string {
	if o == nil || IsNil(o.CountryIsNot) {
		var ret []string
		return ret
	}
	return o.CountryIsNot
}

// GetCountryIsNotOk returns a tuple with the CountryIsNot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetCountryIsNotOk() ([]string, bool) {
	if o == nil || IsNil(o.CountryIsNot) {
		return nil, false
	}
	return o.CountryIsNot, true
}

// HasCountryIsNot returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasCountryIsNot() bool {
	if o != nil && !IsNil(o.CountryIsNot) {
		return true
	}

	return false
}

// SetCountryIsNot gets a reference to the given []string and assigns it to the CountryIsNot field.
func (o *V2RuleAuthRequest) SetCountryIsNot(v []string) {
	o.CountryIsNot = v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *V2RuleAuthRequest) SetMethod(v string) {
	o.Method = &v
}

// GetMethodIs returns the MethodIs field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetMethodIs() []string {
	if o == nil || IsNil(o.MethodIs) {
		var ret []string
		return ret
	}
	return o.MethodIs
}

// GetMethodIsOk returns a tuple with the MethodIs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetMethodIsOk() ([]string, bool) {
	if o == nil || IsNil(o.MethodIs) {
		return nil, false
	}
	return o.MethodIs, true
}

// HasMethodIs returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasMethodIs() bool {
	if o != nil && !IsNil(o.MethodIs) {
		return true
	}

	return false
}

// SetMethodIs gets a reference to the given []string and assigns it to the MethodIs field.
func (o *V2RuleAuthRequest) SetMethodIs(v []string) {
	o.MethodIs = v
}

// GetMethodIsNot returns the MethodIsNot field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetMethodIsNot() []string {
	if o == nil || IsNil(o.MethodIsNot) {
		var ret []string
		return ret
	}
	return o.MethodIsNot
}

// GetMethodIsNotOk returns a tuple with the MethodIsNot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetMethodIsNotOk() ([]string, bool) {
	if o == nil || IsNil(o.MethodIsNot) {
		return nil, false
	}
	return o.MethodIsNot, true
}

// HasMethodIsNot returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasMethodIsNot() bool {
	if o != nil && !IsNil(o.MethodIsNot) {
		return true
	}

	return false
}

// SetMethodIsNot gets a reference to the given []string and assigns it to the MethodIsNot field.
func (o *V2RuleAuthRequest) SetMethodIsNot(v []string) {
	o.MethodIsNot = v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *V2RuleAuthRequest) SetIp(v string) {
	o.Ip = &v
}

// GetIpIs returns the IpIs field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetIpIs() []string {
	if o == nil || IsNil(o.IpIs) {
		var ret []string
		return ret
	}
	return o.IpIs
}

// GetIpIsOk returns a tuple with the IpIs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetIpIsOk() ([]string, bool) {
	if o == nil || IsNil(o.IpIs) {
		return nil, false
	}
	return o.IpIs, true
}

// HasIpIs returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasIpIs() bool {
	if o != nil && !IsNil(o.IpIs) {
		return true
	}

	return false
}

// SetIpIs gets a reference to the given []string and assigns it to the IpIs field.
func (o *V2RuleAuthRequest) SetIpIs(v []string) {
	o.IpIs = v
}

// GetIpIsNot returns the IpIsNot field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetIpIsNot() []string {
	if o == nil || IsNil(o.IpIsNot) {
		var ret []string
		return ret
	}
	return o.IpIsNot
}

// GetIpIsNotOk returns a tuple with the IpIsNot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetIpIsNotOk() ([]string, bool) {
	if o == nil || IsNil(o.IpIsNot) {
		return nil, false
	}
	return o.IpIsNot, true
}

// HasIpIsNot returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasIpIsNot() bool {
	if o != nil && !IsNil(o.IpIsNot) {
		return true
	}

	return false
}

// SetIpIsNot gets a reference to the given []string and assigns it to the IpIsNot field.
func (o *V2RuleAuthRequest) SetIpIsNot(v []string) {
	o.IpIsNot = v
}

// GetTo returns the To field value
func (o *V2RuleAuthRequest) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *V2RuleAuthRequest) SetTo(v string) {
	o.To = v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *V2RuleAuthRequest) SetHost(v string) {
	o.Host = &v
}

// GetAuthUser returns the AuthUser field value
func (o *V2RuleAuthRequest) GetAuthUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthUser
}

// GetAuthUserOk returns a tuple with the AuthUser field value
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetAuthUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthUser, true
}

// SetAuthUser sets field value
func (o *V2RuleAuthRequest) SetAuthUser(v string) {
	o.AuthUser = v
}

// GetAuthPass returns the AuthPass field value
func (o *V2RuleAuthRequest) GetAuthPass() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthPass
}

// GetAuthPassOk returns a tuple with the AuthPass field value
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetAuthPassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthPass, true
}

// SetAuthPass sets field value
func (o *V2RuleAuthRequest) SetAuthPass(v string) {
	o.AuthPass = v
}

// GetDisableSslVerify returns the DisableSslVerify field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetDisableSslVerify() bool {
	if o == nil || IsNil(o.DisableSslVerify) {
		var ret bool
		return ret
	}
	return *o.DisableSslVerify
}

// GetDisableSslVerifyOk returns a tuple with the DisableSslVerify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetDisableSslVerifyOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableSslVerify) {
		return nil, false
	}
	return o.DisableSslVerify, true
}

// HasDisableSslVerify returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasDisableSslVerify() bool {
	if o != nil && !IsNil(o.DisableSslVerify) {
		return true
	}

	return false
}

// SetDisableSslVerify gets a reference to the given bool and assigns it to the DisableSslVerify field.
func (o *V2RuleAuthRequest) SetDisableSslVerify(v bool) {
	o.DisableSslVerify = &v
}

// GetCacheLifetime returns the CacheLifetime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *V2RuleAuthRequest) GetCacheLifetime() string {
	if o == nil || IsNil(o.CacheLifetime.Get()) {
		var ret string
		return ret
	}
	return *o.CacheLifetime.Get()
}

// GetCacheLifetimeOk returns a tuple with the CacheLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2RuleAuthRequest) GetCacheLifetimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CacheLifetime.Get(), o.CacheLifetime.IsSet()
}

// HasCacheLifetime returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasCacheLifetime() bool {
	if o != nil && o.CacheLifetime.IsSet() {
		return true
	}

	return false
}

// SetCacheLifetime gets a reference to the given NullableString and assigns it to the CacheLifetime field.
func (o *V2RuleAuthRequest) SetCacheLifetime(v string) {
	o.CacheLifetime.Set(&v)
}
// SetCacheLifetimeNil sets the value for CacheLifetime to be an explicit nil
func (o *V2RuleAuthRequest) SetCacheLifetimeNil() {
	o.CacheLifetime.Set(nil)
}

// UnsetCacheLifetime ensures that no value is present for CacheLifetime, not even an explicit nil
func (o *V2RuleAuthRequest) UnsetCacheLifetime() {
	o.CacheLifetime.Unset()
}

// GetOnlyProxy404 returns the OnlyProxy404 field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetOnlyProxy404() bool {
	if o == nil || IsNil(o.OnlyProxy404) {
		var ret bool
		return ret
	}
	return *o.OnlyProxy404
}

// GetOnlyProxy404Ok returns a tuple with the OnlyProxy404 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetOnlyProxy404Ok() (*bool, bool) {
	if o == nil || IsNil(o.OnlyProxy404) {
		return nil, false
	}
	return o.OnlyProxy404, true
}

// HasOnlyProxy404 returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasOnlyProxy404() bool {
	if o != nil && !IsNil(o.OnlyProxy404) {
		return true
	}

	return false
}

// SetOnlyProxy404 gets a reference to the given bool and assigns it to the OnlyProxy404 field.
func (o *V2RuleAuthRequest) SetOnlyProxy404(v bool) {
	o.OnlyProxy404 = &v
}

// GetInjectHeaders returns the InjectHeaders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *V2RuleAuthRequest) GetInjectHeaders() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.InjectHeaders
}

// GetInjectHeadersOk returns a tuple with the InjectHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2RuleAuthRequest) GetInjectHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.InjectHeaders) {
		return nil, false
	}
	return &o.InjectHeaders, true
}

// HasInjectHeaders returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasInjectHeaders() bool {
	if o != nil && !IsNil(o.InjectHeaders) {
		return true
	}

	return false
}

// SetInjectHeaders gets a reference to the given map[string]string and assigns it to the InjectHeaders field.
func (o *V2RuleAuthRequest) SetInjectHeaders(v map[string]string) {
	o.InjectHeaders = v
}

// GetProxyStripHeaders returns the ProxyStripHeaders field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetProxyStripHeaders() []string {
	if o == nil || IsNil(o.ProxyStripHeaders) {
		var ret []string
		return ret
	}
	return o.ProxyStripHeaders
}

// GetProxyStripHeadersOk returns a tuple with the ProxyStripHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetProxyStripHeadersOk() ([]string, bool) {
	if o == nil || IsNil(o.ProxyStripHeaders) {
		return nil, false
	}
	return o.ProxyStripHeaders, true
}

// HasProxyStripHeaders returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasProxyStripHeaders() bool {
	if o != nil && !IsNil(o.ProxyStripHeaders) {
		return true
	}

	return false
}

// SetProxyStripHeaders gets a reference to the given []string and assigns it to the ProxyStripHeaders field.
func (o *V2RuleAuthRequest) SetProxyStripHeaders(v []string) {
	o.ProxyStripHeaders = v
}

// GetProxyStripRequestHeaders returns the ProxyStripRequestHeaders field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetProxyStripRequestHeaders() []string {
	if o == nil || IsNil(o.ProxyStripRequestHeaders) {
		var ret []string
		return ret
	}
	return o.ProxyStripRequestHeaders
}

// GetProxyStripRequestHeadersOk returns a tuple with the ProxyStripRequestHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetProxyStripRequestHeadersOk() ([]string, bool) {
	if o == nil || IsNil(o.ProxyStripRequestHeaders) {
		return nil, false
	}
	return o.ProxyStripRequestHeaders, true
}

// HasProxyStripRequestHeaders returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasProxyStripRequestHeaders() bool {
	if o != nil && !IsNil(o.ProxyStripRequestHeaders) {
		return true
	}

	return false
}

// SetProxyStripRequestHeaders gets a reference to the given []string and assigns it to the ProxyStripRequestHeaders field.
func (o *V2RuleAuthRequest) SetProxyStripRequestHeaders(v []string) {
	o.ProxyStripRequestHeaders = v
}

// GetOriginTimeout returns the OriginTimeout field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetOriginTimeout() string {
	if o == nil || IsNil(o.OriginTimeout) {
		var ret string
		return ret
	}
	return *o.OriginTimeout
}

// GetOriginTimeoutOk returns a tuple with the OriginTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetOriginTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.OriginTimeout) {
		return nil, false
	}
	return o.OriginTimeout, true
}

// HasOriginTimeout returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasOriginTimeout() bool {
	if o != nil && !IsNil(o.OriginTimeout) {
		return true
	}

	return false
}

// SetOriginTimeout gets a reference to the given string and assigns it to the OriginTimeout field.
func (o *V2RuleAuthRequest) SetOriginTimeout(v string) {
	o.OriginTimeout = &v
}

// GetFailoverMode returns the FailoverMode field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetFailoverMode() bool {
	if o == nil || IsNil(o.FailoverMode) {
		var ret bool
		return ret
	}
	return *o.FailoverMode
}

// GetFailoverModeOk returns a tuple with the FailoverMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetFailoverModeOk() (*bool, bool) {
	if o == nil || IsNil(o.FailoverMode) {
		return nil, false
	}
	return o.FailoverMode, true
}

// HasFailoverMode returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasFailoverMode() bool {
	if o != nil && !IsNil(o.FailoverMode) {
		return true
	}

	return false
}

// SetFailoverMode gets a reference to the given bool and assigns it to the FailoverMode field.
func (o *V2RuleAuthRequest) SetFailoverMode(v bool) {
	o.FailoverMode = &v
}

// GetFailoverOriginTtfb returns the FailoverOriginTtfb field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetFailoverOriginTtfb() string {
	if o == nil || IsNil(o.FailoverOriginTtfb) {
		var ret string
		return ret
	}
	return *o.FailoverOriginTtfb
}

// GetFailoverOriginTtfbOk returns a tuple with the FailoverOriginTtfb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetFailoverOriginTtfbOk() (*string, bool) {
	if o == nil || IsNil(o.FailoverOriginTtfb) {
		return nil, false
	}
	return o.FailoverOriginTtfb, true
}

// HasFailoverOriginTtfb returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasFailoverOriginTtfb() bool {
	if o != nil && !IsNil(o.FailoverOriginTtfb) {
		return true
	}

	return false
}

// SetFailoverOriginTtfb gets a reference to the given string and assigns it to the FailoverOriginTtfb field.
func (o *V2RuleAuthRequest) SetFailoverOriginTtfb(v string) {
	o.FailoverOriginTtfb = &v
}

// GetFailoverOriginStatusCodes returns the FailoverOriginStatusCodes field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetFailoverOriginStatusCodes() []string {
	if o == nil || IsNil(o.FailoverOriginStatusCodes) {
		var ret []string
		return ret
	}
	return o.FailoverOriginStatusCodes
}

// GetFailoverOriginStatusCodesOk returns a tuple with the FailoverOriginStatusCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetFailoverOriginStatusCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.FailoverOriginStatusCodes) {
		return nil, false
	}
	return o.FailoverOriginStatusCodes, true
}

// HasFailoverOriginStatusCodes returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasFailoverOriginStatusCodes() bool {
	if o != nil && !IsNil(o.FailoverOriginStatusCodes) {
		return true
	}

	return false
}

// SetFailoverOriginStatusCodes gets a reference to the given []string and assigns it to the FailoverOriginStatusCodes field.
func (o *V2RuleAuthRequest) SetFailoverOriginStatusCodes(v []string) {
	o.FailoverOriginStatusCodes = v
}

// GetFailoverLifetime returns the FailoverLifetime field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetFailoverLifetime() string {
	if o == nil || IsNil(o.FailoverLifetime) {
		var ret string
		return ret
	}
	return *o.FailoverLifetime
}

// GetFailoverLifetimeOk returns a tuple with the FailoverLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetFailoverLifetimeOk() (*string, bool) {
	if o == nil || IsNil(o.FailoverLifetime) {
		return nil, false
	}
	return o.FailoverLifetime, true
}

// HasFailoverLifetime returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasFailoverLifetime() bool {
	if o != nil && !IsNil(o.FailoverLifetime) {
		return true
	}

	return false
}

// SetFailoverLifetime gets a reference to the given string and assigns it to the FailoverLifetime field.
func (o *V2RuleAuthRequest) SetFailoverLifetime(v string) {
	o.FailoverLifetime = &v
}

// GetNotify returns the Notify field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetNotify() string {
	if o == nil || IsNil(o.Notify) {
		var ret string
		return ret
	}
	return *o.Notify
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetNotifyOk() (*string, bool) {
	if o == nil || IsNil(o.Notify) {
		return nil, false
	}
	return o.Notify, true
}

// HasNotify returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasNotify() bool {
	if o != nil && !IsNil(o.Notify) {
		return true
	}

	return false
}

// SetNotify gets a reference to the given string and assigns it to the Notify field.
func (o *V2RuleAuthRequest) SetNotify(v string) {
	o.Notify = &v
}

// GetNotifyConfig returns the NotifyConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *V2RuleAuthRequest) GetNotifyConfig() V2RuleProxyActionAllOfNotifyConfig {
	if o == nil || IsNil(o.NotifyConfig.Get()) {
		var ret V2RuleProxyActionAllOfNotifyConfig
		return ret
	}
	return *o.NotifyConfig.Get()
}

// GetNotifyConfigOk returns a tuple with the NotifyConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2RuleAuthRequest) GetNotifyConfigOk() (*V2RuleProxyActionAllOfNotifyConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.NotifyConfig.Get(), o.NotifyConfig.IsSet()
}

// HasNotifyConfig returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasNotifyConfig() bool {
	if o != nil && o.NotifyConfig.IsSet() {
		return true
	}

	return false
}

// SetNotifyConfig gets a reference to the given NullableV2RuleProxyActionAllOfNotifyConfig and assigns it to the NotifyConfig field.
func (o *V2RuleAuthRequest) SetNotifyConfig(v V2RuleProxyActionAllOfNotifyConfig) {
	o.NotifyConfig.Set(&v)
}
// SetNotifyConfigNil sets the value for NotifyConfig to be an explicit nil
func (o *V2RuleAuthRequest) SetNotifyConfigNil() {
	o.NotifyConfig.Set(nil)
}

// UnsetNotifyConfig ensures that no value is present for NotifyConfig, not even an explicit nil
func (o *V2RuleAuthRequest) UnsetNotifyConfig() {
	o.NotifyConfig.Unset()
}

// GetWafEnabled returns the WafEnabled field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetWafEnabled() bool {
	if o == nil || IsNil(o.WafEnabled) {
		var ret bool
		return ret
	}
	return *o.WafEnabled
}

// GetWafEnabledOk returns a tuple with the WafEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetWafEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.WafEnabled) {
		return nil, false
	}
	return o.WafEnabled, true
}

// HasWafEnabled returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasWafEnabled() bool {
	if o != nil && !IsNil(o.WafEnabled) {
		return true
	}

	return false
}

// SetWafEnabled gets a reference to the given bool and assigns it to the WafEnabled field.
func (o *V2RuleAuthRequest) SetWafEnabled(v bool) {
	o.WafEnabled = &v
}

// GetWafConfig returns the WafConfig field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetWafConfig() WafConfig {
	if o == nil || IsNil(o.WafConfig) {
		var ret WafConfig
		return ret
	}
	return *o.WafConfig
}

// GetWafConfigOk returns a tuple with the WafConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetWafConfigOk() (*WafConfig, bool) {
	if o == nil || IsNil(o.WafConfig) {
		return nil, false
	}
	return o.WafConfig, true
}

// HasWafConfig returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasWafConfig() bool {
	if o != nil && !IsNil(o.WafConfig) {
		return true
	}

	return false
}

// SetWafConfig gets a reference to the given WafConfig and assigns it to the WafConfig field.
func (o *V2RuleAuthRequest) SetWafConfig(v WafConfig) {
	o.WafConfig = &v
}

// GetProxyAlertEnabled returns the ProxyAlertEnabled field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetProxyAlertEnabled() bool {
	if o == nil || IsNil(o.ProxyAlertEnabled) {
		var ret bool
		return ret
	}
	return *o.ProxyAlertEnabled
}

// GetProxyAlertEnabledOk returns a tuple with the ProxyAlertEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetProxyAlertEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ProxyAlertEnabled) {
		return nil, false
	}
	return o.ProxyAlertEnabled, true
}

// HasProxyAlertEnabled returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasProxyAlertEnabled() bool {
	if o != nil && !IsNil(o.ProxyAlertEnabled) {
		return true
	}

	return false
}

// SetProxyAlertEnabled gets a reference to the given bool and assigns it to the ProxyAlertEnabled field.
func (o *V2RuleAuthRequest) SetProxyAlertEnabled(v bool) {
	o.ProxyAlertEnabled = &v
}

// GetProxyInlineFnEnabled returns the ProxyInlineFnEnabled field value if set, zero value otherwise.
func (o *V2RuleAuthRequest) GetProxyInlineFnEnabled() bool {
	if o == nil || IsNil(o.ProxyInlineFnEnabled) {
		var ret bool
		return ret
	}
	return *o.ProxyInlineFnEnabled
}

// GetProxyInlineFnEnabledOk returns a tuple with the ProxyInlineFnEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2RuleAuthRequest) GetProxyInlineFnEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ProxyInlineFnEnabled) {
		return nil, false
	}
	return o.ProxyInlineFnEnabled, true
}

// HasProxyInlineFnEnabled returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasProxyInlineFnEnabled() bool {
	if o != nil && !IsNil(o.ProxyInlineFnEnabled) {
		return true
	}

	return false
}

// SetProxyInlineFnEnabled gets a reference to the given bool and assigns it to the ProxyInlineFnEnabled field.
func (o *V2RuleAuthRequest) SetProxyInlineFnEnabled(v bool) {
	o.ProxyInlineFnEnabled = &v
}

// GetQuantCloudSelection returns the QuantCloudSelection field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *V2RuleAuthRequest) GetQuantCloudSelection() V2RuleProxyActionAllOfQuantCloudSelection {
	if o == nil || IsNil(o.QuantCloudSelection.Get()) {
		var ret V2RuleProxyActionAllOfQuantCloudSelection
		return ret
	}
	return *o.QuantCloudSelection.Get()
}

// GetQuantCloudSelectionOk returns a tuple with the QuantCloudSelection field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2RuleAuthRequest) GetQuantCloudSelectionOk() (*V2RuleProxyActionAllOfQuantCloudSelection, bool) {
	if o == nil {
		return nil, false
	}
	return o.QuantCloudSelection.Get(), o.QuantCloudSelection.IsSet()
}

// HasQuantCloudSelection returns a boolean if a field has been set.
func (o *V2RuleAuthRequest) HasQuantCloudSelection() bool {
	if o != nil && o.QuantCloudSelection.IsSet() {
		return true
	}

	return false
}

// SetQuantCloudSelection gets a reference to the given NullableV2RuleProxyActionAllOfQuantCloudSelection and assigns it to the QuantCloudSelection field.
func (o *V2RuleAuthRequest) SetQuantCloudSelection(v V2RuleProxyActionAllOfQuantCloudSelection) {
	o.QuantCloudSelection.Set(&v)
}
// SetQuantCloudSelectionNil sets the value for QuantCloudSelection to be an explicit nil
func (o *V2RuleAuthRequest) SetQuantCloudSelectionNil() {
	o.QuantCloudSelection.Set(nil)
}

// UnsetQuantCloudSelection ensures that no value is present for QuantCloudSelection, not even an explicit nil
func (o *V2RuleAuthRequest) UnsetQuantCloudSelection() {
	o.QuantCloudSelection.Unset()
}

func (o V2RuleAuthRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2RuleAuthRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["error"] = o.Error
	toSerialize["domain"] = o.Domain
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	toSerialize["url"] = o.Url
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.CountryIs) {
		toSerialize["country_is"] = o.CountryIs
	}
	if !IsNil(o.CountryIsNot) {
		toSerialize["country_is_not"] = o.CountryIsNot
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.MethodIs) {
		toSerialize["method_is"] = o.MethodIs
	}
	if !IsNil(o.MethodIsNot) {
		toSerialize["method_is_not"] = o.MethodIsNot
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.IpIs) {
		toSerialize["ip_is"] = o.IpIs
	}
	if !IsNil(o.IpIsNot) {
		toSerialize["ip_is_not"] = o.IpIsNot
	}
	toSerialize["to"] = o.To
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	toSerialize["auth_user"] = o.AuthUser
	toSerialize["auth_pass"] = o.AuthPass
	if !IsNil(o.DisableSslVerify) {
		toSerialize["disable_ssl_verify"] = o.DisableSslVerify
	}
	if o.CacheLifetime.IsSet() {
		toSerialize["cache_lifetime"] = o.CacheLifetime.Get()
	}
	if !IsNil(o.OnlyProxy404) {
		toSerialize["only_proxy_404"] = o.OnlyProxy404
	}
	if o.InjectHeaders != nil {
		toSerialize["inject_headers"] = o.InjectHeaders
	}
	if !IsNil(o.ProxyStripHeaders) {
		toSerialize["proxy_strip_headers"] = o.ProxyStripHeaders
	}
	if !IsNil(o.ProxyStripRequestHeaders) {
		toSerialize["proxy_strip_request_headers"] = o.ProxyStripRequestHeaders
	}
	if !IsNil(o.OriginTimeout) {
		toSerialize["origin_timeout"] = o.OriginTimeout
	}
	if !IsNil(o.FailoverMode) {
		toSerialize["failover_mode"] = o.FailoverMode
	}
	if !IsNil(o.FailoverOriginTtfb) {
		toSerialize["failover_origin_ttfb"] = o.FailoverOriginTtfb
	}
	if !IsNil(o.FailoverOriginStatusCodes) {
		toSerialize["failover_origin_status_codes"] = o.FailoverOriginStatusCodes
	}
	if !IsNil(o.FailoverLifetime) {
		toSerialize["failover_lifetime"] = o.FailoverLifetime
	}
	if !IsNil(o.Notify) {
		toSerialize["notify"] = o.Notify
	}
	if o.NotifyConfig.IsSet() {
		toSerialize["notify_config"] = o.NotifyConfig.Get()
	}
	if !IsNil(o.WafEnabled) {
		toSerialize["waf_enabled"] = o.WafEnabled
	}
	if !IsNil(o.WafConfig) {
		toSerialize["waf_config"] = o.WafConfig
	}
	if !IsNil(o.ProxyAlertEnabled) {
		toSerialize["proxy_alert_enabled"] = o.ProxyAlertEnabled
	}
	if !IsNil(o.ProxyInlineFnEnabled) {
		toSerialize["proxy_inline_fn_enabled"] = o.ProxyInlineFnEnabled
	}
	if o.QuantCloudSelection.IsSet() {
		toSerialize["quant_cloud_selection"] = o.QuantCloudSelection.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V2RuleAuthRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"error",
		"domain",
		"url",
		"to",
		"auth_user",
		"auth_pass",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2RuleAuthRequest := _V2RuleAuthRequest{}

	err = json.Unmarshal(data, &varV2RuleAuthRequest)

	if err != nil {
		return err
	}

	*o = V2RuleAuthRequest(varV2RuleAuthRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "error")
		delete(additionalProperties, "domain")
		delete(additionalProperties, "name")
		delete(additionalProperties, "uuid")
		delete(additionalProperties, "weight")
		delete(additionalProperties, "disabled")
		delete(additionalProperties, "url")
		delete(additionalProperties, "country")
		delete(additionalProperties, "country_is")
		delete(additionalProperties, "country_is_not")
		delete(additionalProperties, "method")
		delete(additionalProperties, "method_is")
		delete(additionalProperties, "method_is_not")
		delete(additionalProperties, "ip")
		delete(additionalProperties, "ip_is")
		delete(additionalProperties, "ip_is_not")
		delete(additionalProperties, "to")
		delete(additionalProperties, "host")
		delete(additionalProperties, "auth_user")
		delete(additionalProperties, "auth_pass")
		delete(additionalProperties, "disable_ssl_verify")
		delete(additionalProperties, "cache_lifetime")
		delete(additionalProperties, "only_proxy_404")
		delete(additionalProperties, "inject_headers")
		delete(additionalProperties, "proxy_strip_headers")
		delete(additionalProperties, "proxy_strip_request_headers")
		delete(additionalProperties, "origin_timeout")
		delete(additionalProperties, "failover_mode")
		delete(additionalProperties, "failover_origin_ttfb")
		delete(additionalProperties, "failover_origin_status_codes")
		delete(additionalProperties, "failover_lifetime")
		delete(additionalProperties, "notify")
		delete(additionalProperties, "notify_config")
		delete(additionalProperties, "waf_enabled")
		delete(additionalProperties, "waf_config")
		delete(additionalProperties, "proxy_alert_enabled")
		delete(additionalProperties, "proxy_inline_fn_enabled")
		delete(additionalProperties, "quant_cloud_selection")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV2RuleAuthRequest struct {
	value *V2RuleAuthRequest
	isSet bool
}

func (v NullableV2RuleAuthRequest) Get() *V2RuleAuthRequest {
	return v.value
}

func (v *NullableV2RuleAuthRequest) Set(val *V2RuleAuthRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2RuleAuthRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2RuleAuthRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2RuleAuthRequest(val *V2RuleAuthRequest) *NullableV2RuleAuthRequest {
	return &NullableV2RuleAuthRequest{value: val, isSet: true}
}

func (v NullableV2RuleAuthRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2RuleAuthRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


