/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.15.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"time"
)

// checks if the TokensList200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokensList200ResponseInner{}

// TokensList200ResponseInner struct for TokensList200ResponseInner
type TokensList200ResponseInner struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	LastUsed NullableTime `json:"last_used,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TokensList200ResponseInner TokensList200ResponseInner

// NewTokensList200ResponseInner instantiates a new TokensList200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokensList200ResponseInner() *TokensList200ResponseInner {
	this := TokensList200ResponseInner{}
	return &this
}

// NewTokensList200ResponseInnerWithDefaults instantiates a new TokensList200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokensList200ResponseInnerWithDefaults() *TokensList200ResponseInner {
	this := TokensList200ResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TokensList200ResponseInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokensList200ResponseInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TokensList200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *TokensList200ResponseInner) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TokensList200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokensList200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TokensList200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TokensList200ResponseInner) SetName(v string) {
	o.Name = &v
}

// GetLastUsed returns the LastUsed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokensList200ResponseInner) GetLastUsed() time.Time {
	if o == nil || IsNil(o.LastUsed.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUsed.Get()
}

// GetLastUsedOk returns a tuple with the LastUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokensList200ResponseInner) GetLastUsedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsed.Get(), o.LastUsed.IsSet()
}

// HasLastUsed returns a boolean if a field has been set.
func (o *TokensList200ResponseInner) HasLastUsed() bool {
	if o != nil && o.LastUsed.IsSet() {
		return true
	}

	return false
}

// SetLastUsed gets a reference to the given NullableTime and assigns it to the LastUsed field.
func (o *TokensList200ResponseInner) SetLastUsed(v time.Time) {
	o.LastUsed.Set(&v)
}
// SetLastUsedNil sets the value for LastUsed to be an explicit nil
func (o *TokensList200ResponseInner) SetLastUsedNil() {
	o.LastUsed.Set(nil)
}

// UnsetLastUsed ensures that no value is present for LastUsed, not even an explicit nil
func (o *TokensList200ResponseInner) UnsetLastUsed() {
	o.LastUsed.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *TokensList200ResponseInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokensList200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *TokensList200ResponseInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *TokensList200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o TokensList200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokensList200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.LastUsed.IsSet() {
		toSerialize["last_used"] = o.LastUsed.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TokensList200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	varTokensList200ResponseInner := _TokensList200ResponseInner{}

	err = json.Unmarshal(data, &varTokensList200ResponseInner)

	if err != nil {
		return err
	}

	*o = TokensList200ResponseInner(varTokensList200ResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "last_used")
		delete(additionalProperties, "created_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTokensList200ResponseInner struct {
	value *TokensList200ResponseInner
	isSet bool
}

func (v NullableTokensList200ResponseInner) Get() *TokensList200ResponseInner {
	return v.value
}

func (v *NullableTokensList200ResponseInner) Set(val *TokensList200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTokensList200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTokensList200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokensList200ResponseInner(val *TokensList200ResponseInner) *NullableTokensList200ResponseInner {
	return &NullableTokensList200ResponseInner{value: val, isSet: true}
}

func (v NullableTokensList200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokensList200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


