/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
)

// checks if the ListAITools200ResponseToolsInnerToolSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAITools200ResponseToolsInnerToolSpec{}

// ListAITools200ResponseToolsInnerToolSpec struct for ListAITools200ResponseToolsInnerToolSpec
type ListAITools200ResponseToolsInnerToolSpec struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	InputSchema *ListAITools200ResponseToolsInnerToolSpecInputSchema `json:"inputSchema,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAITools200ResponseToolsInnerToolSpec ListAITools200ResponseToolsInnerToolSpec

// NewListAITools200ResponseToolsInnerToolSpec instantiates a new ListAITools200ResponseToolsInnerToolSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAITools200ResponseToolsInnerToolSpec() *ListAITools200ResponseToolsInnerToolSpec {
	this := ListAITools200ResponseToolsInnerToolSpec{}
	return &this
}

// NewListAITools200ResponseToolsInnerToolSpecWithDefaults instantiates a new ListAITools200ResponseToolsInnerToolSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAITools200ResponseToolsInnerToolSpecWithDefaults() *ListAITools200ResponseToolsInnerToolSpec {
	this := ListAITools200ResponseToolsInnerToolSpec{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ListAITools200ResponseToolsInnerToolSpec) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAITools200ResponseToolsInnerToolSpec) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ListAITools200ResponseToolsInnerToolSpec) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ListAITools200ResponseToolsInnerToolSpec) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ListAITools200ResponseToolsInnerToolSpec) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAITools200ResponseToolsInnerToolSpec) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ListAITools200ResponseToolsInnerToolSpec) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ListAITools200ResponseToolsInnerToolSpec) SetDescription(v string) {
	o.Description = &v
}

// GetInputSchema returns the InputSchema field value if set, zero value otherwise.
func (o *ListAITools200ResponseToolsInnerToolSpec) GetInputSchema() ListAITools200ResponseToolsInnerToolSpecInputSchema {
	if o == nil || IsNil(o.InputSchema) {
		var ret ListAITools200ResponseToolsInnerToolSpecInputSchema
		return ret
	}
	return *o.InputSchema
}

// GetInputSchemaOk returns a tuple with the InputSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAITools200ResponseToolsInnerToolSpec) GetInputSchemaOk() (*ListAITools200ResponseToolsInnerToolSpecInputSchema, bool) {
	if o == nil || IsNil(o.InputSchema) {
		return nil, false
	}
	return o.InputSchema, true
}

// HasInputSchema returns a boolean if a field has been set.
func (o *ListAITools200ResponseToolsInnerToolSpec) HasInputSchema() bool {
	if o != nil && !IsNil(o.InputSchema) {
		return true
	}

	return false
}

// SetInputSchema gets a reference to the given ListAITools200ResponseToolsInnerToolSpecInputSchema and assigns it to the InputSchema field.
func (o *ListAITools200ResponseToolsInnerToolSpec) SetInputSchema(v ListAITools200ResponseToolsInnerToolSpecInputSchema) {
	o.InputSchema = &v
}

func (o ListAITools200ResponseToolsInnerToolSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAITools200ResponseToolsInnerToolSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.InputSchema) {
		toSerialize["inputSchema"] = o.InputSchema
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAITools200ResponseToolsInnerToolSpec) UnmarshalJSON(data []byte) (err error) {
	varListAITools200ResponseToolsInnerToolSpec := _ListAITools200ResponseToolsInnerToolSpec{}

	err = json.Unmarshal(data, &varListAITools200ResponseToolsInnerToolSpec)

	if err != nil {
		return err
	}

	*o = ListAITools200ResponseToolsInnerToolSpec(varListAITools200ResponseToolsInnerToolSpec)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "inputSchema")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAITools200ResponseToolsInnerToolSpec struct {
	value *ListAITools200ResponseToolsInnerToolSpec
	isSet bool
}

func (v NullableListAITools200ResponseToolsInnerToolSpec) Get() *ListAITools200ResponseToolsInnerToolSpec {
	return v.value
}

func (v *NullableListAITools200ResponseToolsInnerToolSpec) Set(val *ListAITools200ResponseToolsInnerToolSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableListAITools200ResponseToolsInnerToolSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableListAITools200ResponseToolsInnerToolSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAITools200ResponseToolsInnerToolSpec(val *ListAITools200ResponseToolsInnerToolSpec) *NullableListAITools200ResponseToolsInnerToolSpec {
	return &NullableListAITools200ResponseToolsInnerToolSpec{value: val, isSet: true}
}

func (v NullableListAITools200ResponseToolsInnerToolSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAITools200ResponseToolsInnerToolSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


