/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
)

// checks if the ChatInferenceRequestToolConfigToolsInnerToolSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatInferenceRequestToolConfigToolsInnerToolSpec{}

// ChatInferenceRequestToolConfigToolsInnerToolSpec struct for ChatInferenceRequestToolConfigToolsInnerToolSpec
type ChatInferenceRequestToolConfigToolsInnerToolSpec struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	InputSchema *ChatInferenceRequestToolConfigToolsInnerToolSpecInputSchema `json:"inputSchema,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChatInferenceRequestToolConfigToolsInnerToolSpec ChatInferenceRequestToolConfigToolsInnerToolSpec

// NewChatInferenceRequestToolConfigToolsInnerToolSpec instantiates a new ChatInferenceRequestToolConfigToolsInnerToolSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatInferenceRequestToolConfigToolsInnerToolSpec() *ChatInferenceRequestToolConfigToolsInnerToolSpec {
	this := ChatInferenceRequestToolConfigToolsInnerToolSpec{}
	return &this
}

// NewChatInferenceRequestToolConfigToolsInnerToolSpecWithDefaults instantiates a new ChatInferenceRequestToolConfigToolsInnerToolSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatInferenceRequestToolConfigToolsInnerToolSpecWithDefaults() *ChatInferenceRequestToolConfigToolsInnerToolSpec {
	this := ChatInferenceRequestToolConfigToolsInnerToolSpec{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) SetDescription(v string) {
	o.Description = &v
}

// GetInputSchema returns the InputSchema field value if set, zero value otherwise.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) GetInputSchema() ChatInferenceRequestToolConfigToolsInnerToolSpecInputSchema {
	if o == nil || IsNil(o.InputSchema) {
		var ret ChatInferenceRequestToolConfigToolsInnerToolSpecInputSchema
		return ret
	}
	return *o.InputSchema
}

// GetInputSchemaOk returns a tuple with the InputSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) GetInputSchemaOk() (*ChatInferenceRequestToolConfigToolsInnerToolSpecInputSchema, bool) {
	if o == nil || IsNil(o.InputSchema) {
		return nil, false
	}
	return o.InputSchema, true
}

// HasInputSchema returns a boolean if a field has been set.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) HasInputSchema() bool {
	if o != nil && !IsNil(o.InputSchema) {
		return true
	}

	return false
}

// SetInputSchema gets a reference to the given ChatInferenceRequestToolConfigToolsInnerToolSpecInputSchema and assigns it to the InputSchema field.
func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) SetInputSchema(v ChatInferenceRequestToolConfigToolsInnerToolSpecInputSchema) {
	o.InputSchema = &v
}

func (o ChatInferenceRequestToolConfigToolsInnerToolSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatInferenceRequestToolConfigToolsInnerToolSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.InputSchema) {
		toSerialize["inputSchema"] = o.InputSchema
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChatInferenceRequestToolConfigToolsInnerToolSpec) UnmarshalJSON(data []byte) (err error) {
	varChatInferenceRequestToolConfigToolsInnerToolSpec := _ChatInferenceRequestToolConfigToolsInnerToolSpec{}

	err = json.Unmarshal(data, &varChatInferenceRequestToolConfigToolsInnerToolSpec)

	if err != nil {
		return err
	}

	*o = ChatInferenceRequestToolConfigToolsInnerToolSpec(varChatInferenceRequestToolConfigToolsInnerToolSpec)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "inputSchema")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChatInferenceRequestToolConfigToolsInnerToolSpec struct {
	value *ChatInferenceRequestToolConfigToolsInnerToolSpec
	isSet bool
}

func (v NullableChatInferenceRequestToolConfigToolsInnerToolSpec) Get() *ChatInferenceRequestToolConfigToolsInnerToolSpec {
	return v.value
}

func (v *NullableChatInferenceRequestToolConfigToolsInnerToolSpec) Set(val *ChatInferenceRequestToolConfigToolsInnerToolSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableChatInferenceRequestToolConfigToolsInnerToolSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableChatInferenceRequestToolConfigToolsInnerToolSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatInferenceRequestToolConfigToolsInnerToolSpec(val *ChatInferenceRequestToolConfigToolsInnerToolSpec) *NullableChatInferenceRequestToolConfigToolsInnerToolSpec {
	return &NullableChatInferenceRequestToolConfigToolsInnerToolSpec{value: val, isSet: true}
}

func (v NullableChatInferenceRequestToolConfigToolsInnerToolSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatInferenceRequestToolConfigToolsInnerToolSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


