/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateCronJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCronJobRequest{}

// CreateCronJobRequest struct for CreateCronJobRequest
type CreateCronJobRequest struct {
	Name string `json:"name"`
	Description NullableString `json:"description,omitempty"`
	ScheduleExpression string `json:"scheduleExpression"`
	Command []string `json:"command"`
	TargetContainerName NullableString `json:"targetContainerName,omitempty"`
	IsEnabled NullableBool `json:"isEnabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateCronJobRequest CreateCronJobRequest

// NewCreateCronJobRequest instantiates a new CreateCronJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCronJobRequest(name string, scheduleExpression string, command []string) *CreateCronJobRequest {
	this := CreateCronJobRequest{}
	this.Name = name
	this.ScheduleExpression = scheduleExpression
	this.Command = command
	var isEnabled bool = true
	this.IsEnabled = *NewNullableBool(&isEnabled)
	return &this
}

// NewCreateCronJobRequestWithDefaults instantiates a new CreateCronJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCronJobRequestWithDefaults() *CreateCronJobRequest {
	this := CreateCronJobRequest{}
	var isEnabled bool = true
	this.IsEnabled = *NewNullableBool(&isEnabled)
	return &this
}

// GetName returns the Name field value
func (o *CreateCronJobRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCronJobRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCronJobRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCronJobRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCronJobRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateCronJobRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateCronJobRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateCronJobRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateCronJobRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetScheduleExpression returns the ScheduleExpression field value
func (o *CreateCronJobRequest) GetScheduleExpression() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScheduleExpression
}

// GetScheduleExpressionOk returns a tuple with the ScheduleExpression field value
// and a boolean to check if the value has been set.
func (o *CreateCronJobRequest) GetScheduleExpressionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduleExpression, true
}

// SetScheduleExpression sets field value
func (o *CreateCronJobRequest) SetScheduleExpression(v string) {
	o.ScheduleExpression = v
}

// GetCommand returns the Command field value
func (o *CreateCronJobRequest) GetCommand() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *CreateCronJobRequest) GetCommandOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Command, true
}

// SetCommand sets field value
func (o *CreateCronJobRequest) SetCommand(v []string) {
	o.Command = v
}

// GetTargetContainerName returns the TargetContainerName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCronJobRequest) GetTargetContainerName() string {
	if o == nil || IsNil(o.TargetContainerName.Get()) {
		var ret string
		return ret
	}
	return *o.TargetContainerName.Get()
}

// GetTargetContainerNameOk returns a tuple with the TargetContainerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCronJobRequest) GetTargetContainerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetContainerName.Get(), o.TargetContainerName.IsSet()
}

// HasTargetContainerName returns a boolean if a field has been set.
func (o *CreateCronJobRequest) HasTargetContainerName() bool {
	if o != nil && o.TargetContainerName.IsSet() {
		return true
	}

	return false
}

// SetTargetContainerName gets a reference to the given NullableString and assigns it to the TargetContainerName field.
func (o *CreateCronJobRequest) SetTargetContainerName(v string) {
	o.TargetContainerName.Set(&v)
}
// SetTargetContainerNameNil sets the value for TargetContainerName to be an explicit nil
func (o *CreateCronJobRequest) SetTargetContainerNameNil() {
	o.TargetContainerName.Set(nil)
}

// UnsetTargetContainerName ensures that no value is present for TargetContainerName, not even an explicit nil
func (o *CreateCronJobRequest) UnsetTargetContainerName() {
	o.TargetContainerName.Unset()
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCronJobRequest) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.IsEnabled.Get()
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCronJobRequest) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsEnabled.Get(), o.IsEnabled.IsSet()
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *CreateCronJobRequest) HasIsEnabled() bool {
	if o != nil && o.IsEnabled.IsSet() {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given NullableBool and assigns it to the IsEnabled field.
func (o *CreateCronJobRequest) SetIsEnabled(v bool) {
	o.IsEnabled.Set(&v)
}
// SetIsEnabledNil sets the value for IsEnabled to be an explicit nil
func (o *CreateCronJobRequest) SetIsEnabledNil() {
	o.IsEnabled.Set(nil)
}

// UnsetIsEnabled ensures that no value is present for IsEnabled, not even an explicit nil
func (o *CreateCronJobRequest) UnsetIsEnabled() {
	o.IsEnabled.Unset()
}

func (o CreateCronJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCronJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["scheduleExpression"] = o.ScheduleExpression
	toSerialize["command"] = o.Command
	if o.TargetContainerName.IsSet() {
		toSerialize["targetContainerName"] = o.TargetContainerName.Get()
	}
	if o.IsEnabled.IsSet() {
		toSerialize["isEnabled"] = o.IsEnabled.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateCronJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"scheduleExpression",
		"command",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCronJobRequest := _CreateCronJobRequest{}

	err = json.Unmarshal(data, &varCreateCronJobRequest)

	if err != nil {
		return err
	}

	*o = CreateCronJobRequest(varCreateCronJobRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "scheduleExpression")
		delete(additionalProperties, "command")
		delete(additionalProperties, "targetContainerName")
		delete(additionalProperties, "isEnabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateCronJobRequest struct {
	value *CreateCronJobRequest
	isSet bool
}

func (v NullableCreateCronJobRequest) Get() *CreateCronJobRequest {
	return v.value
}

func (v *NullableCreateCronJobRequest) Set(val *CreateCronJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCronJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCronJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCronJobRequest(val *CreateCronJobRequest) *NullableCreateCronJobRequest {
	return &NullableCreateCronJobRequest{value: val, isSet: true}
}

func (v NullableCreateCronJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCronJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


