/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
)

// checks if the GetVectorCollection200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVectorCollection200Response{}

// GetVectorCollection200Response struct for GetVectorCollection200Response
type GetVectorCollection200Response struct {
	Collection *GetVectorCollection200ResponseCollection `json:"collection,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetVectorCollection200Response GetVectorCollection200Response

// NewGetVectorCollection200Response instantiates a new GetVectorCollection200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVectorCollection200Response() *GetVectorCollection200Response {
	this := GetVectorCollection200Response{}
	return &this
}

// NewGetVectorCollection200ResponseWithDefaults instantiates a new GetVectorCollection200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVectorCollection200ResponseWithDefaults() *GetVectorCollection200Response {
	this := GetVectorCollection200Response{}
	return &this
}

// GetCollection returns the Collection field value if set, zero value otherwise.
func (o *GetVectorCollection200Response) GetCollection() GetVectorCollection200ResponseCollection {
	if o == nil || IsNil(o.Collection) {
		var ret GetVectorCollection200ResponseCollection
		return ret
	}
	return *o.Collection
}

// GetCollectionOk returns a tuple with the Collection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVectorCollection200Response) GetCollectionOk() (*GetVectorCollection200ResponseCollection, bool) {
	if o == nil || IsNil(o.Collection) {
		return nil, false
	}
	return o.Collection, true
}

// HasCollection returns a boolean if a field has been set.
func (o *GetVectorCollection200Response) HasCollection() bool {
	if o != nil && !IsNil(o.Collection) {
		return true
	}

	return false
}

// SetCollection gets a reference to the given GetVectorCollection200ResponseCollection and assigns it to the Collection field.
func (o *GetVectorCollection200Response) SetCollection(v GetVectorCollection200ResponseCollection) {
	o.Collection = &v
}

func (o GetVectorCollection200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVectorCollection200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Collection) {
		toSerialize["collection"] = o.Collection
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetVectorCollection200Response) UnmarshalJSON(data []byte) (err error) {
	varGetVectorCollection200Response := _GetVectorCollection200Response{}

	err = json.Unmarshal(data, &varGetVectorCollection200Response)

	if err != nil {
		return err
	}

	*o = GetVectorCollection200Response(varGetVectorCollection200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "collection")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetVectorCollection200Response struct {
	value *GetVectorCollection200Response
	isSet bool
}

func (v NullableGetVectorCollection200Response) Get() *GetVectorCollection200Response {
	return v.value
}

func (v *NullableGetVectorCollection200Response) Set(val *GetVectorCollection200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVectorCollection200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVectorCollection200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVectorCollection200Response(val *GetVectorCollection200Response) *NullableGetVectorCollection200Response {
	return &NullableGetVectorCollection200Response{value: val, isSet: true}
}

func (v NullableGetVectorCollection200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVectorCollection200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


