/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"fmt"
)

// checks if the ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document{}

// ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document struct for ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document
type ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document struct {
	Format string `json:"format"`
	Name string `json:"name"`
	Source ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3DocumentSource `json:"source"`
	AdditionalProperties map[string]interface{}
}

type _ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document

// NewChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document instantiates a new ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document(format string, name string, source ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3DocumentSource) *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document {
	this := ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document{}
	this.Format = format
	this.Name = name
	this.Source = source
	return &this
}

// NewChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3DocumentWithDefaults instantiates a new ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3DocumentWithDefaults() *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document {
	this := ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document{}
	return &this
}

// GetFormat returns the Format field value
func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) SetFormat(v string) {
	o.Format = v
}

// GetName returns the Name field value
func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) SetName(v string) {
	o.Name = v
}

// GetSource returns the Source field value
func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) GetSource() ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3DocumentSource {
	if o == nil {
		var ret ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3DocumentSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) GetSourceOk() (*ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3DocumentSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) SetSource(v ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3DocumentSource) {
	o.Source = v
}

func (o ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["format"] = o.Format
	toSerialize["name"] = o.Name
	toSerialize["source"] = o.Source

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"format",
		"name",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document := _ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document{}

	err = json.Unmarshal(data, &varChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document)

	if err != nil {
		return err
	}

	*o = ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document(varChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "format")
		delete(additionalProperties, "name")
		delete(additionalProperties, "source")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document struct {
	value *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document
	isSet bool
}

func (v NullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) Get() *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document {
	return v.value
}

func (v *NullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) Set(val *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) {
	v.value = val
	v.isSet = true
}

func (v NullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) IsSet() bool {
	return v.isSet
}

func (v *NullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document(val *ChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) *NullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document {
	return &NullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document{value: val, isSet: true}
}

func (v NullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatInferenceRequestMessagesInnerContentOneOfInnerOneOf3Document) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


