/*
Quant administration API

The Quant administration API provides programmatic access to manage projects within your available organizations. 

API version: 2.0.0
Contact: apiteam@quantcdn.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData{}

// OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData struct for OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData
type OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData struct {
	Rules []Rule `json:"rules,omitempty"`
}

// NewOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData instantiates a new OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData() *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData {
	this := OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData{}
	return &this
}

// NewOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseDataWithDefaults instantiates a new OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseDataWithDefaults() *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData {
	this := OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData{}
	return &this
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) GetRules() []Rule {
	if o == nil || IsNil(o.Rules) {
		var ret []Rule
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) GetRulesOk() ([]Rule, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []Rule and assigns it to the Rules field.
func (o *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) SetRules(v []Rule) {
	o.Rules = v
}

func (o OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	return toSerialize, nil
}

type NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData struct {
	value *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData
	isSet bool
}

func (v NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) Get() *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData {
	return v.value
}

func (v *NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) Set(val *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData(val *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) *NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData {
	return &NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData{value: val, isSet: true}
}

func (v NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


