/*
Quant administration API

The Quant administration API provides programmatic access to manage projects within your available organizations. 

API version: 2.0.0
Contact: apiteam@quantcdn.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response{}

// OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response struct for OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response
type OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response struct {
	Data *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData `json:"data,omitempty"`
}

// NewOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response instantiates a new OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response() *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response {
	this := OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response{}
	return &this
}

// NewOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseWithDefaults instantiates a new OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseWithDefaults() *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response {
	this := OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) GetData() OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) GetDataOk() (*OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData and assigns it to the Data field.
func (o *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) SetData(v OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200ResponseData) {
	o.Data = &v
}

func (o OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response struct {
	value *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response
	isSet bool
}

func (v NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) Get() *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response {
	return v.value
}

func (v *NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) Set(val *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response(val *OrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) *NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response {
	return &NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response{value: val, isSet: true}
}

func (v NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsOrganizationProjectsProjectRulesRedirectRuleGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


