/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
)

// checks if the CreateApplicationRequestEnvironmentInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplicationRequestEnvironmentInner{}

// CreateApplicationRequestEnvironmentInner struct for CreateApplicationRequestEnvironmentInner
type CreateApplicationRequestEnvironmentInner struct {
	// Environment variable name
	Name *string `json:"name,omitempty"`
	// Environment variable value
	Value *string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateApplicationRequestEnvironmentInner CreateApplicationRequestEnvironmentInner

// NewCreateApplicationRequestEnvironmentInner instantiates a new CreateApplicationRequestEnvironmentInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplicationRequestEnvironmentInner() *CreateApplicationRequestEnvironmentInner {
	this := CreateApplicationRequestEnvironmentInner{}
	return &this
}

// NewCreateApplicationRequestEnvironmentInnerWithDefaults instantiates a new CreateApplicationRequestEnvironmentInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplicationRequestEnvironmentInnerWithDefaults() *CreateApplicationRequestEnvironmentInner {
	this := CreateApplicationRequestEnvironmentInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateApplicationRequestEnvironmentInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationRequestEnvironmentInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateApplicationRequestEnvironmentInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateApplicationRequestEnvironmentInner) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CreateApplicationRequestEnvironmentInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationRequestEnvironmentInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CreateApplicationRequestEnvironmentInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CreateApplicationRequestEnvironmentInner) SetValue(v string) {
	o.Value = &v
}

func (o CreateApplicationRequestEnvironmentInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplicationRequestEnvironmentInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateApplicationRequestEnvironmentInner) UnmarshalJSON(data []byte) (err error) {
	varCreateApplicationRequestEnvironmentInner := _CreateApplicationRequestEnvironmentInner{}

	err = json.Unmarshal(data, &varCreateApplicationRequestEnvironmentInner)

	if err != nil {
		return err
	}

	*o = CreateApplicationRequestEnvironmentInner(varCreateApplicationRequestEnvironmentInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateApplicationRequestEnvironmentInner struct {
	value *CreateApplicationRequestEnvironmentInner
	isSet bool
}

func (v NullableCreateApplicationRequestEnvironmentInner) Get() *CreateApplicationRequestEnvironmentInner {
	return v.value
}

func (v *NullableCreateApplicationRequestEnvironmentInner) Set(val *CreateApplicationRequestEnvironmentInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationRequestEnvironmentInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationRequestEnvironmentInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationRequestEnvironmentInner(val *CreateApplicationRequestEnvironmentInner) *NullableCreateApplicationRequestEnvironmentInner {
	return &NullableCreateApplicationRequestEnvironmentInner{value: val, isSet: true}
}

func (v NullableCreateApplicationRequestEnvironmentInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationRequestEnvironmentInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


