/*
QuantCDN API

Unified API for QuantCDN Admin and QuantCloud Platform services

API version: 4.17.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quantadmingo

import (
	"encoding/json"
	"fmt"
)

// checks if the RestoreDatabaseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestoreDatabaseRequest{}

// RestoreDatabaseRequest struct for RestoreDatabaseRequest
type RestoreDatabaseRequest struct {
	// The backup ID to restore (must match path param)
	BackupId string `json:"backupId"`
	// Must be true to confirm existing data will be overwritten
	AcknowledgeDataloss bool `json:"acknowledgeDataloss"`
	AdditionalProperties map[string]interface{}
}

type _RestoreDatabaseRequest RestoreDatabaseRequest

// NewRestoreDatabaseRequest instantiates a new RestoreDatabaseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestoreDatabaseRequest(backupId string, acknowledgeDataloss bool) *RestoreDatabaseRequest {
	this := RestoreDatabaseRequest{}
	this.BackupId = backupId
	this.AcknowledgeDataloss = acknowledgeDataloss
	return &this
}

// NewRestoreDatabaseRequestWithDefaults instantiates a new RestoreDatabaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestoreDatabaseRequestWithDefaults() *RestoreDatabaseRequest {
	this := RestoreDatabaseRequest{}
	return &this
}

// GetBackupId returns the BackupId field value
func (o *RestoreDatabaseRequest) GetBackupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BackupId
}

// GetBackupIdOk returns a tuple with the BackupId field value
// and a boolean to check if the value has been set.
func (o *RestoreDatabaseRequest) GetBackupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackupId, true
}

// SetBackupId sets field value
func (o *RestoreDatabaseRequest) SetBackupId(v string) {
	o.BackupId = v
}

// GetAcknowledgeDataloss returns the AcknowledgeDataloss field value
func (o *RestoreDatabaseRequest) GetAcknowledgeDataloss() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AcknowledgeDataloss
}

// GetAcknowledgeDatalossOk returns a tuple with the AcknowledgeDataloss field value
// and a boolean to check if the value has been set.
func (o *RestoreDatabaseRequest) GetAcknowledgeDatalossOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AcknowledgeDataloss, true
}

// SetAcknowledgeDataloss sets field value
func (o *RestoreDatabaseRequest) SetAcknowledgeDataloss(v bool) {
	o.AcknowledgeDataloss = v
}

func (o RestoreDatabaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestoreDatabaseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backupId"] = o.BackupId
	toSerialize["acknowledgeDataloss"] = o.AcknowledgeDataloss

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RestoreDatabaseRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backupId",
		"acknowledgeDataloss",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestoreDatabaseRequest := _RestoreDatabaseRequest{}

	err = json.Unmarshal(data, &varRestoreDatabaseRequest)

	if err != nil {
		return err
	}

	*o = RestoreDatabaseRequest(varRestoreDatabaseRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "backupId")
		delete(additionalProperties, "acknowledgeDataloss")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRestoreDatabaseRequest struct {
	value *RestoreDatabaseRequest
	isSet bool
}

func (v NullableRestoreDatabaseRequest) Get() *RestoreDatabaseRequest {
	return v.value
}

func (v *NullableRestoreDatabaseRequest) Set(val *RestoreDatabaseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRestoreDatabaseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRestoreDatabaseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestoreDatabaseRequest(val *RestoreDatabaseRequest) *NullableRestoreDatabaseRequest {
	return &NullableRestoreDatabaseRequest{value: val, isSet: true}
}

func (v NullableRestoreDatabaseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestoreDatabaseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


